[SERVICE]
    Flush        2
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    DB                /tmp/docker-tail.db
    Mem_Buf_Limit     32MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[OUTPUT]
    Name   file
    Match  docker.*
    Path   /output
    File   containers.log
    Format plain
