const fs=require('node:fs'),path=require('node:path');const {unseal}=require('./runtime.cjs');
function endpoint(raw){const u=new URL(raw);if(u.username||u.password||u.search||u.hash)throw Error('Endpoint должен быть без пароля, параметров и фрагмента');if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('Нужен HTTPS или локальный HTTP');return u.toString().replace(/\/$/,'');}
async function jsonRequest(url,headers,body,signal){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body),signal,redirect:'error'});if(!r.ok)throw Error('Провайдер вернул HTTP '+r.status);const reader=r.body.getReader();let n=0,parts=[];while(true){const p=await reader.read();if(p.done)break;n+=p.value.length;if(n>1000000){await reader.cancel();throw Error('Ответ провайдера слишком большой');}parts.push(p.value);}try{return JSON.parse(Buffer.concat(parts).toString('utf8'));}catch{throw Error('Провайдер вернул некорректный JSON');}}
async function generate(provider,system,user){const base=endpoint(provider.endpoint),key=provider.secret?unseal(provider.secret):'';const signal=AbortSignal.timeout(60000);let text;
 if(provider.protocol==='openai'){const r=await jsonRequest(base+'/chat/completions',key?{Authorization:'Bearer '+key}:{},{model:provider.model,...(new URL(base).hostname==='api.openai.com'?{max_completion_tokens:1600}:{max_tokens:1600}),messages:[{role:'system',content:system},{role:'user',content:user}]},signal);text=r.choices?.[0]?.message?.content;}
 else if(provider.protocol==='anthropic'){const r=await jsonRequest(base+'/messages',{'x-api-key':key,'anthropic-version':'2023-06-01'},{model:provider.model,max_tokens:1600,system,messages:[{role:'user',content:user}]},signal);text=r.content?.filter(v=>v.type==='text').map(v=>v.text).join('');}
 else if(provider.protocol==='gemini'){const r=await jsonRequest(base+'/models/'+encodeURIComponent(provider.model.replace(/^models\//,''))+':generateContent',{'x-goog-api-key':key},{systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:user}]}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:1600}},signal);text=r.candidates?.[0]?.content?.parts?.map(v=>v.text||'').join('');}
 else if(provider.protocol==='ollama'){const r=await jsonRequest(base+'/chat',key?{Authorization:'Bearer '+key}:{},{model:provider.model,stream:false,format:'json',options:{num_predict:1600},messages:[{role:'system',content:system},{role:'user',content:user}]},signal);text=r.message?.content;}
 else if(provider.protocol==='custom'){if(!/^[A-Za-z0-9_-]+\.cjs$/.test(provider.adapter||''))throw Error('Некорректный файл адаптера');const file=path.join(__dirname,'adapters',provider.adapter);if(!fs.existsSync(file))throw Error('Файл адаптера отсутствует');try{text=await Promise.race([require(file).generate({endpoint:base,model:provider.model,apiKey:key,system,user,signal}),new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('Таймаут адаптера')),{once:true}))]);}catch{throw Error('Ошибка собственного адаптера. Проверьте его реализацию локально.');}}
 else throw Error('Неизвестный протокол');
 if(typeof text!=='string'||text.length>50000)throw Error('Провайдер не вернул текст');return text;
}
function choices(text,candidates,kinds){let parsed;try{parsed=JSON.parse(text.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));}catch{throw Error('ИИ вернул некорректный JSON');}const rows=parsed.actions;if(!Array.isArray(rows)||rows.length>3)throw Error('Ожидается actions, до 3 действий');const seen=new Set();return rows.map(a=>{const source=candidates.find(c=>c.tweet_id===a.source_id);if(!source||!kinds.includes(a.kind)||typeof a.reason!=='string'||a.reason.length>500)throw Error('Неизвестное действие или источник');const text=['post','reply'].includes(a.kind)?a.text:null;if(text!==null&&(typeof text!=='string'||!text.trim()||Array.from(text).length>220))throw Error('Текст ИИ должен быть от 1 до 220 символов');if(text&&/https?:\/\//i.test(text))throw Error('ИИ не должен добавлять ссылки — источник добавит система');if(text&&/(?:гарантирован\w*|guaranteed)\s+(?:прибыл\w*|profit|return)/i.test(text))throw Error('Обещания гарантированной доходности запрещены');const id=a.kind+':'+source.tweet_id;if(seen.has(id))throw Error('Повтор действия');seen.add(id);return {kind:a.kind,text,reason:a.reason,source};});}
module.exports={endpoint,generate,choices};
