import { performance } from "node:perf_hooks";
import { buildBlockchainAiSnapshot, compactBlockchainSnapshotForAi } from "../lib/trade/chain/ai-snapshot.ts";

const now = Date.now();
const walletPerf = Array.from({length: 50}, (_, i) => ({ wallet:`W${i}`, winRate: i%2?0.7:0.4, medianHoldSlots:100+i, realizedPnlSol:i, unrealizedPnlSol:i/2, realizedRatio:0.66, tradeCount:100-i, avgTradeSizeSol:2, avgTradeSizeQuote:2, quoteMint:"SOL", isSmartMoney:i<8, historySampleSize:120-i }));
const walletBehavior = Array.from({length: 80}, (_, i) => ({ wallet:`W${i}`, activeWindowCount:4-(i%4), windows:{}, flowAcceleration15mVs1h:0.1, buyPersistence:0.5, sellPersistence:0.1 }));
const ledgers = Array.from({length: 80}, (_, i) => ({ wallet:`W${i}`, totalPnl:i-40, tradeCount:80-i, available:true, unit:"sol", quoteMint:"SOL", historyComplete:true, costBasisComplete:true, completeFromObservedTrades:true, orderingComplete:true, unmatchedSellTokens:0 }));
const clusters = Array.from({length: 40}, (_, i) => ({clusterId:`C${i}`,wallets:[`W${i}`,`W${i+1}`],sources:["temporal_coactivity"],verifiedFundingEdges:0,bundleLinks:0,coactivityLinks:1,firstSeenTs:now/1000-3600,lastSeenTs:now/1000,activeBuckets:4,persistence01:0.5,observationCount:10,persistedFirstSeenAt:null,persistedLastSeenAt:null}));
const chain:any={
  full:{mint:"M".repeat(32),asOf:now,checks:Array.from({length:10},(_,i)=>({id:`c${i}`,status:i===0?"warn":"ok",source:"rpc",fetchedAt:now})),largestAccounts:[],holders:[],liquidity:{liquidityUsd:250000,volLiqRatio:1,slippage:{pct1:1,pct5:5,pct10:10},lpConcentrationPct:20},dev:{wallets:[],remainingPct:null,realizedPnlSol:null,cexDeposits:[],lastActivityTs:null},clusters:{bundles:2,walletSharePct:4,sniperCount:5,washSharePct:3,smartInflowSol:20},events:Array.from({length:50},(_,i)=>({ts:now-i*1000,kind:"large_swap"})),quality:null,truncated:false,sources:["rpc"]},
  drift:{holdersDrift:10,top10Drift:-2},groups:[],verdictFields:{safetyFail:false},
  quality:{concentration:{top10Pct:25,adjustedTop10Pct:20},walletAge:{},firstBlocks:[],snipers:{},bundles:{},funding:{},insiders:{},wash:{walletSharePct:2},smartMoney:{netInflowSol:15},flows:[],coordinatedSelling:{},creator:{historicalTokens:100,historicalMigrationRate:.2,historicalReached300kRate:.1},exitLiquidity:{},bondingCurve:null,migration:{},transactions:{},crossToken:{},holderQuality:{},walletProfiles:Array.from({length:50},(_,i)=>({wallet:`W${i}`})),trends:[],anomalies:[],dimensions:{},evidence:{holders:{source:"rpc",available:true,complete:true,fetchedAt:now,coveragePct:100},recentTrades:{source:"rpc",available:true,complete:true,fetchedAt:now,coveragePct:100}},evidenceCompletenessPct:95},
  qualityV34:{walletPerformance:walletPerf,concentrationDynamics:{velocity1h:-.02},orderFlow:{ofi5m:{value:.2,coverage:1},ofi15m:{value:.3,coverage:1},ofi1h:{value:.1,coverage:1},whaleNetFlow1h:10,retailNetFlow1h:5},bundleAnalyticsV2:{bundleCount:2,currentSupplyPct:4,bundlePnlPct:30},fundingTree:{verifiedEdges:4,coverage:1},washTradingV2:{walletSharePct:2,circularPatterns:1},lifecycle:{stage:"acceleration",confidence:.8,rulesTriggered:[]},contradictions:[],compositeScores:{smartMoneyScore:{value:70,confidence:{value:.8}},coordinationScoreV2:{value:20,confidence:{value:.8}},organicGrowthScore:{value:80,confidence:{value:.8}},distributionRiskScore:{value:30,confidence:{value:.8}},demandMomentumScore:{value:75,confidence:{value:.8}},narrativeMomentumScore:{value:null,confidence:{value:.1}}},confidence:{value:.8,components:{},penalties:[]}},
  qualityV35:{walletBehavior,costBasisLedgers:ledgers,walletClusters:clusters,liquidityAdjustedFlow:{m15:{signedPressure01:.2,coverage:1},h1:{signedPressure01:.1,coverage:1}},holderCohortMigration:{},outcomeReplay:{horizons:{}},snapshot:{}}
}; chain.full.quality=chain.quality;
const dev:any={available:true,creator:"C".repeat(32),mint:chain.full.mint,fetchedAt:now,source:"local-cache",warning:null,analytics:{previousLaunches:500,migrationCount:100,migrationRate:.2,ath:{observedCount:400,coverage:.8,medianUsd:50000},thresholds:{reached100k:{rate:.3,coverage:.8},reached300k:{rate:.1,coverage:.8},reached1m:{rate:.02,coverage:.8}},rolling100k:{},trend:{state:"stable"},cadence:{},recurringNetwork:{}},outcomes:{retentionDays:14,horizons:{},postMigration:{},recent:Array.from({length:12},(_,i)=>({mint:`T${i}`,returnsPct:{"1h":i}}))},forensics:{}};
for(let i=0;i<20;i++){const s=buildBlockchainAiSnapshot({mint:chain.full.mint,chain,devHistory:dev}); JSON.stringify(compactBlockchainSnapshotForAi(s));}
const times=[]; let bytes=0;
for(let i=0;i<200;i++){const t=performance.now(); const s=buildBlockchainAiSnapshot({mint:chain.full.mint,chain,devHistory:dev}); const raw=JSON.stringify(compactBlockchainSnapshotForAi(s)); bytes=Buffer.byteLength(raw); times.push(performance.now()-t);}
times.sort((a,b)=>a-b); const avg=times.reduce((a,b)=>a+b,0)/times.length; const med=times[Math.floor(times.length*.5)]; const p95=times[Math.floor(times.length*.95)];
console.log(JSON.stringify({avgMs:avg,medianMs:med,p95Ms:p95,compactBytes:bytes},null,2));
