'use client';
import {useCallback,useEffect,useState} from 'react';
type Provider={id:string;label:string;protocol:string;endpoint:string;model:string;adapter?:string;hasKey:boolean};
type Config={account_name:string;enabled:boolean;expected_handle:string;provider_id:string;language:string;style:string;kinds:string[];interval_minutes:number;daily_limit:number;start_hour:number;end_hour:number;next_run:string;last_message?:string};
type Job={id:string;account_name:string;kind:string;content:string;status:string;reason:string;message:string;result_url?:string;scheduled_at:string};
type Overview={providers:Provider[];configs:Config[];accounts:{name:string;status:string}[];control:{paused:boolean;heartbeat:string|null};jobs:Job[];sources?:{count:number;latest:string|null}};
const kinds:{[k:string]:string}={post:'Твиты',reply:'Ответы',like:'Лайки',repost:'Репосты',follow:'Подписки'};
const cls='w-full rounded border border-white/20 bg-black/30 p-2 text-sm text-white';
export default function AutopostPanel(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [provider,setProvider]=useState({id:'main',label:'Основной ИИ',protocol:'openai',endpoint:'https://api.openai.com/v1',model:'',adapter:'',apiKey:'',clearKey:false});
 const [cfg,setCfg]=useState({name:'',expected:'',enabled:false,provider:'main',language:'ru',style:'Короткие наблюдения о мемкоинах Solana. Указывай источник, не выдумывай факты.',kinds:['post','reply','like','repost','follow'],interval:120,limit:4,start:9,end:23});
 const reload=useCallback(async()=>{try{const r=await fetch('/api/integrations/x-collector?action=autopost-overview',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки');}},[]);
 useEffect(()=>{void reload();const timer=setInterval(()=>void reload(),10000);return()=>clearInterval(timer);},[reload]);
 async function action(action:string,values:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/integrations/x-collector',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'autopost-'+action,...values})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message||'Сохранено');if(action==='provider-save')setProvider(p=>({...p,apiKey:''}));await reload();}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить действие');}finally{setBusy(false);}}
 function selectAccount(name:string){const saved=data?.configs.find(c=>c.account_name===name);setCfg(saved?{name,expected:saved.expected_handle,enabled:saved.enabled,provider:saved.provider_id,language:saved.language,style:saved.style,kinds:saved.kinds,interval:saved.interval_minutes,limit:saved.daily_limit,start:saved.start_hour,end:saved.end_hour}:{...cfg,name,expected:name,enabled:false});}
 const online=data?.control.heartbeat&&Date.now()-Number(data.control.heartbeat)<600000;
 return <section className="space-y-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Автопостинг и активность X</h2><p className="text-sm text-white/50">Выбор событий → ИИ → очередь → X → история и статистика.</p></div><button type="button" disabled={busy||!data} onClick={()=>void action('pause',{paused:!data?.control.paused})} className="rounded border border-neon-green/40 px-4 py-2 text-neon-green disabled:opacity-40">{data?.control.paused?'Включить агента':'Остановить агента'}</button></div>
 {error&&<p role="alert" className="text-red-300">{error}</p>}{message&&<p role="status" className="text-neon-green">{message}</p>}
 <div className="grid gap-3 md:grid-cols-3">{[['Агент',data?.control.paused?'Остановлен':'Включён'],['Исполнитель',online?'Работает / выполняет задачу':'Нет свежего сигнала'],['Очередь',String(data?.jobs.filter(j=>['queued','running'].includes(j.status)).length||0)]].map(([title,value])=><div key={title} className="rounded-xl border border-white/10 p-4"><p className="text-xs text-white/50">{title}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div>
 <p className="text-xs text-white/50">Исполнитель запускается отдельно: <code>node scripts/autopost-worker.cjs</code> в x-collector. Общая остановка блокирует действия агента; ручные публикации и сбор метрик продолжаются. Уже отправленное действие отменить нельзя.</p>
 <p className="text-sm text-white/60">Постов в базе за сутки: {data?.sources?.count??0}. {data?.sources?.count===0?'Для выбора событий добавьте аккаунт сбора и запустите сборщик X Collector. Без источников ИИ пропускает цикл.':'ИИ выбирает из свежих событий о мемкоинах Solana.'}</p>
 <div className="grid gap-5 xl:grid-cols-2"><form className="space-y-3 rounded-xl border border-white/10 p-4" onSubmit={e=>{e.preventDefault();void action('provider-save',provider);}}><h3 className="font-semibold">Провайдер ИИ</h3><p className="text-xs text-white/50">Подключите один или несколько API. Для несовместимого API используйте собственный адаптер.</p><select className={cls} value="" onChange={e=>{const p=data?.providers.find(p=>p.id===e.target.value);if(p)setProvider({id:p.id,label:p.label,protocol:p.protocol,endpoint:p.endpoint,model:p.model,adapter:p.adapter||'',apiKey:'',clearKey:false});}}><option value="">Редактировать сохранённого провайдера…</option>{data?.providers.map(p=><option key={p.id} value={p.id}>{p.label} · {p.model}{p.hasKey?' · ключ сохранён':''}</option>)}</select>
 <label className="block text-sm">ID<input required pattern="[A-Za-z0-9_-]{1,64}" className={cls} value={provider.id} onChange={e=>setProvider({...provider,id:e.target.value})}/></label><label className="block text-sm">Название<input required className={cls} value={provider.label} onChange={e=>setProvider({...provider,label:e.target.value})}/></label>
 <label className="block text-sm">Протокол<select className={cls} value={provider.protocol} onChange={e=>setProvider({...provider,protocol:e.target.value,endpoint:({openai:'https://api.openai.com/v1',anthropic:'https://api.anthropic.com/v1',gemini:'https://generativelanguage.googleapis.com/v1beta',ollama:'http://127.0.0.1:11434/api',custom:''} as Record<string,string>)[e.target.value]})}>{[['openai','OpenAI-совместимый'],['anthropic','Anthropic Messages'],['gemini','Gemini'],['ollama','Ollama'],['custom','Собственный адаптер']].map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label>
 <label className="block text-sm">Базовый адрес API<input required type="url" className={cls} value={provider.endpoint} onChange={e=>setProvider({...provider,endpoint:e.target.value})}/></label><label className="block text-sm">Точное имя модели<input required className={cls} value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})}/></label><label className="block text-sm">API key<input type="password" autoComplete="new-password" className={cls} value={provider.apiKey} placeholder="Пустое поле сохраняет прежний ключ" onChange={e=>setProvider({...provider,apiKey:e.target.value})}/></label><label className="block text-xs"><input type="checkbox" checked={provider.clearKey} onChange={e=>setProvider({...provider,clearKey:e.target.checked})}/> Удалить сохранённый ключ</label>
 {provider.protocol==='custom'&&<label className="block text-sm">Имя файла в scripts/autopost/adapters<input required pattern="[A-Za-z0-9_-]+\.cjs" className={cls} value={provider.adapter} onChange={e=>setProvider({...provider,adapter:e.target.value})}/></label>}
 <p className="text-xs text-white/40">Ключ отправляется только выбранному API. Используйте доверенный адрес. Ключ хранится зашифрованным и не отображается обратно.</p><div className="flex gap-4"><button disabled={busy} className="text-neon-green disabled:opacity-40">Сохранить провайдера</button><button type="button" disabled={busy||!data?.providers.some(p=>p.id===provider.id)} onClick={()=>void action('provider-test',{id:provider.id})} className="text-blue-300 disabled:opacity-40">Проверить сохранённое подключение</button></div></form>
 <form className="space-y-3 rounded-xl border border-white/10 p-4" onSubmit={e=>{e.preventDefault();void action('config-save',cfg);}}><h3 className="font-semibold">Настройки аккаунта</h3><select required className={cls} value={cfg.name} onChange={e=>selectAccount(e.target.value)}><option value="">Выберите аккаунт публикации</option>{data?.accounts.map(a=><option key={a.name} value={a.name}>{a.name} · {a.status}</option>)}</select><label className="block text-sm">Username X<input required pattern="@?[A-Za-z0-9_]{1,15}" className={cls} value={cfg.expected} onChange={e=>setCfg({...cfg,expected:e.target.value})}/></label><select required className={cls} value={cfg.provider} onChange={e=>setCfg({...cfg,provider:e.target.value})}><option value="">Провайдер</option>{data?.providers.map(p=><option key={p.id} value={p.id}>{p.label} · {p.model}</option>)}</select><label className="block text-sm">Язык<input className={cls} maxLength={30} value={cfg.language} onChange={e=>setCfg({...cfg,language:e.target.value})}/></label><label className="block text-sm">Стиль и тематика<textarea className={cls} maxLength={3000} rows={3} value={cfg.style} onChange={e=>setCfg({...cfg,style:e.target.value})}/></label>
 <div className="flex flex-wrap gap-3">{Object.entries(kinds).map(([id,title])=><label key={id} className="text-sm"><input type="checkbox" checked={cfg.kinds.includes(id)} onChange={e=>setCfg({...cfg,kinds:e.target.checked?[...cfg.kinds,id]:cfg.kinds.filter(k=>k!==id)})}/> {title}</label>)}</div><div className="grid grid-cols-2 gap-3">{[['interval','Интервал циклов, минут',5,10080],['limit','Максимум действий в день',1,100],['start','Начало активности, час МСК',0,23],['end','Конец активности, час МСК',0,23]].map(([key,title,min,max])=><label key={String(key)} className="text-sm">{title}<input required type="number" min={Number(min)} max={Number(max)} className={cls} value={Number(cfg[key as keyof typeof cfg])} onChange={e=>setCfg({...cfg,[String(key)]:Number(e.target.value)})}/></label>)}</div><p className="text-xs text-white/40">Одинаковые часы означают весь день. Интервал управляет выбором событий; выбранные действия выполняются без подтверждения.</p><label className="block"><input type="checkbox" checked={cfg.enabled} onChange={e=>setCfg({...cfg,enabled:e.target.checked})}/> Включить этот аккаунт</label><button disabled={busy||!cfg.name||!cfg.kinds.length} className="text-neon-green disabled:opacity-40">Сохранить настройки</button></form></div>
 {data?.configs.length? <div className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Следующие циклы</h3>{data.configs.map(c=><p key={c.account_name} className="mt-2 text-sm text-white/60">{c.account_name} · {c.enabled?'включён':'пауза'} · {new Date(Number(c.next_run)).toLocaleString('ru-RU')} · {c.last_message||'Ещё не запускался'}</p>)}</div>:null}
 <div className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Очередь и история · последние 100 действий</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Аккаунт / действие','Текст и причина','Время','Статус','Результат'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data?.jobs.map(j=><tr key={j.id} className="border-t border-white/10"><td className="p-2">{j.account_name}<br/>{kinds[j.kind]}</td><td className="max-w-lg p-2"><p className="whitespace-pre-wrap">{j.content}</p><p className="text-xs text-white/40">{j.reason}</p></td><td className="p-2">{new Date(Number(j.scheduled_at)).toLocaleString('ru-RU')}</td><td className="p-2">{({queued:'В очереди',running:'Выполняется',published:'Выполнено',failed:'Ошибка до отправки',uncertain:'Проверьте X',cancelled:'Отменено'} as Record<string,string>)[j.status]}<p className="text-xs text-white/40">{j.message}</p></td><td className="p-2">{j.result_url&&<a href={j.result_url} target="_blank" rel="noopener noreferrer" className="text-neon-green underline">Открыть в X</a>}{j.status==='queued'&&<button type="button" disabled={busy} onClick={()=>void action('cancel',{id:j.id})} className="text-red-300">Отменить</button>}</td></tr>)}</tbody></table></div></div>
 </section>;
}
