'use client';
import {useEffect,useState} from 'react';
type Job={id:string;status:string;message:string;url?:string};
export default function PublisherComposer({name,onClose}:{name:string;onClose:()=>void}){
 const [expected,setExpected]=useState(name);const [text,setText]=useState('');const [job,setJob]=useState<Job|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const pending=job&&['opening','sending'].includes(job.status);
 useEffect(()=>{if(!pending||!job)return;let stopped=false,failures=0,inFlight=false;const timer=setInterval(async()=>{if(inFlight)return;inFlight=true;try{const r=await fetch('/api/integrations/x-collector?action=publish-status&id='+encodeURIComponent(job.id),{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);failures=0;if(!stopped)setJob(data);}catch{if(!stopped){setError('Не удалось получить статус. Проверьте очередь и профиль X; повторную отправку не запускайте.');if(++failures>=3)setJob(old=>old?{...old,status:'uncertain',message:'Статус не получен. Проверьте очередь и профиль X.'}:old);}}finally{inFlight=false;}},1500);return()=>{stopped=true;clearInterval(timer);};},[job?.id,pending]);
 async function send(){if(busy||job)return;const id=crypto.randomUUID();setBusy(true);setError('');setJob({id,status:'opening',message:'Запускаем публикацию…'});try{const r=await fetch('/api/integrations/x-collector',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish-start',id,name,expected,text})});const data=await r.json();if(!r.ok){setJob(null);throw Error(data.error);}setJob(data);}catch(e){setError(e instanceof Error?e.message:'Не удалось получить результат. Проверьте профиль X перед повтором.');}finally{setBusy(false);}}
 return <div className="space-y-3 rounded-xl border border-neon-green/30 bg-black/20 p-4"><div className="flex justify-between"><h3 className="font-semibold text-white">Опубликовать твит · {name}</h3><button type="button" disabled={Boolean(pending)||busy} onClick={onClose} className="text-white/60 disabled:opacity-40">Закрыть</button></div><label className="block text-sm text-white/70">Username в X (проверим перед отправкой)<input value={expected} disabled={Boolean(job)||busy} onChange={e=>setExpected(e.target.value)} className="mt-1 block w-full rounded border border-white/20 bg-black/30 p-2 text-white"/></label><label className="block text-sm text-white/70">Текст твита<textarea value={text} disabled={Boolean(job)||busy} onChange={e=>setText(e.target.value)} rows={4} className="mt-1 block w-full rounded border border-white/20 bg-black/30 p-2 text-white"/></label><p className="text-xs text-white/50">{Array.from(text).length} / 280 · Отправка ставит твит в очередь; публикацию выполняет запущенный worker.</p><button type="button" onClick={()=>void send()} disabled={Boolean(job)||busy||!text.trim()||Array.from(text).length>280||!/^@?[A-Za-z0-9_]{1,15}$/.test(expected)} className="rounded border border-neon-green/40 px-4 py-2 text-neon-green disabled:opacity-40">{pending?'Публикуем…':'Опубликовать'}</button>{job&&<p role="status" className="text-sm text-white/80">{job.message}</p>}{job?.url&&<a href={job.url} target="_blank" rel="noopener noreferrer" className="block text-neon-green underline">Открыть опубликованный твит</a>}{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}{job&&['done','failed','uncertain'].includes(job.status)&&<button type="button" onClick={()=>{setJob(null);setText('');setError('');}} className="text-sm text-white/60 underline">Результат проверен — новый твит</button>}</div>;
}
