'use client';
import {useCallback,useEffect,useState} from 'react';
type Post={tweet_id:string;text:string;url:string;views:string|null;likes:string|null;replies:string|null;retweets:string|null;updated_at:string};
type Snapshot={day:string;tweet_id:string;measured_at:string;views:string|null;likes:string|null;replies:string|null;retweets:string|null};
const num=(v:string|null)=>v===null?'Нет данных':BigInt(v).toLocaleString('ru-RU');
export default function PublisherMetrics({name,handle}:{name:string;handle:string}){
 const [data,setData]=useState<{posts:Post[];snapshots:Snapshot[];sync:{id:string;status:string;message:string}[]}|null>(null),[error,setError]=useState(''),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const reload=useCallback(async()=>{try{const r=await fetch('/api/integrations/x-collector?action=autopost-stats&name='+encodeURIComponent(name),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Ошибка статистики');}},[name]);
 useEffect(()=>{void reload();const timer=setInterval(()=>void reload(),15000);return()=>clearInterval(timer);},[reload]);
 async function sync(id:string){setBusy(true);setError('');try{const r=await fetch('/api/integrations/x-collector',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'autopost-sync',name,expected:handle,tweet_id:id})});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);setInput('');await reload();}catch(e){setError(e instanceof Error?e.message:'Ошибка импорта');}finally{setBusy(false);}}
 const points: {day:string;views:number|null;interactions:number|null}[]=[];
 if(data){const byDay=new Map<string,Snapshot[]>();for(const s of data.snapshots){const list=byDay.get(s.day)||[];list.push(s);byDay.set(s.day,list);}const latest=new Map<string,Snapshot>();for(const [day,list] of [...byDay.entries()].sort()){for(const s of list)latest.set(s.tweet_id,s);const rows=[...latest.values()];points.push({day,views:rows.every(r=>r.views===null)?null:rows.reduce((n,r)=>n+Number(r.views||0),0),interactions:rows.every(r=>r.likes===null&&r.replies===null&&r.retweets===null)?null:rows.reduce((n,r)=>n+Number(r.likes||0)+Number(r.replies||0)+Number(r.retweets||0),0)});}}
 const max=Math.max(1,...points.flatMap(p=>[p.views||0,p.interactions||0]));
 return <section className="space-y-3 rounded-xl border border-white/10 p-4"><h4 className="font-semibold text-white">Обновление из X и история метрик</h4><p className="text-xs text-white/50">Посты сохраняются после отправки. Исполнитель обновляет доступные метрики каждые 30 минут для постов за последние 30 дней. Данные доступны с первого успешного измерения; отсутствие показателя не означает ноль.</p><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();const id=input.match(/(?:\/status\/)?(\d{1,25})(?:\?.*)?$/)?.[1];if(id)void sync(id);else setError('Введите ID поста или ссылку на него');}}><input required value={input} onChange={e=>setInput(e.target.value)} placeholder="ID или ссылка на уже опубликованный пост" className="min-w-64 flex-1 rounded border border-white/20 bg-black/30 p-2 text-white"/><button disabled={busy} className="text-neon-green disabled:opacity-40">Импортировать пост</button></form>{error&&<p className="text-red-300">{error}</p>}{message&&<p className="text-neon-green">{message}</p>}
 {points.length>0&&<><div className="flex gap-4 text-xs"><span className="text-green-400">Просмотры</span><span className="text-blue-400">Взаимодействия</span></div><svg viewBox="0 0 640 190" className="w-full" role="img" aria-label="История измеренных метрик"><title>Сумма последних измерений последних 100 отслеживаемых постов по дням</title>{[0,1,2].map(i=><g key={i}><line x1="55" x2="620" y1={20+i*60} y2={20+i*60} stroke="#ffffff20"/><text x="50" y={24+i*60} fill="#aaa" textAnchor="end" fontSize="10">{Math.round(max*(1-i/2))}</text></g>)}{(['views','interactions'] as const).map((metric,m)=><g key={metric}><polyline fill="none" stroke={m?'#60a5fa':'#4ade80'} points={points.filter(p=>p[metric]!==null).map(p=>`${55+points.indexOf(p)*565/Math.max(1,points.length-1)},${140-Number(p[metric])/max*120}`).join(' ')}/>{points.map((p,i)=>p[metric]!==null&&<circle key={p.day} cx={55+i*565/Math.max(1,points.length-1)} cy={140-Number(p[metric])/max*120} r="3" fill={m?'#60a5fa':'#4ade80'}><title>{p.day}: {p[metric]}</title></circle>)}</g>)}<text x="55" y="175" fill="#aaa" fontSize="11">{points[0]?.day}</text><text x="620" y="175" fill="#aaa" textAnchor="end" fontSize="11">{points.at(-1)?.day}</text></svg><p className="text-xs text-white/40">Это история сохранённых измерений. При добавлении постов состав отслеживаемой группы меняется.</p></>}
 <div className="overflow-x-auto"><table className="w-full text-left text-sm text-white"><thead><tr>{['Пост','Просмотры','Лайки','Ответы','Репосты','Измерение / обновление'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data?.posts.map(p=><tr key={p.tweet_id} className="border-t border-white/10"><td className="max-w-lg p-2"><p>{p.text}</p><a href={p.url} target="_blank" rel="noopener noreferrer" className="text-neon-green underline">Открыть в X</a></td>{(['views','likes','replies','retweets'] as const).map(k=><td key={k} className="p-2">{num(p[k])}</td>)}<td className="p-2">{new Date(Number(p.updated_at)).toLocaleString('ru-RU')}<br/><button type="button" disabled={busy} onClick={()=>void sync(p.tweet_id)} className="text-neon-green disabled:opacity-40">Обновить из X</button></td></tr>)}</tbody></table></div>{!data?.posts.length&&<p className="text-sm text-white/50">Импортируйте ранее отправленный тестовый твит по ссылке. Новые посты попадут сюда автоматически.</p>}{data?.sync.map(s=><p key={s.id} className="text-xs text-white/50">{({queued:'Ожидает исполнителя',running:'Получаем данные из X',done:'Обновлено',failed:'Ошибка'} as Record<string,string>)[s.status]||s.status} · {s.message}</p>)}
 </section>;
}
