const {spawn}=require('node:child_process');const path=require('node:path'),fs=require('node:fs');let sourceCollector,historyCollector;
const {claim,eligible}=require('./autopost/queue.cjs');
const {connect}=require('./autopost/runtime.cjs');const {plan,inWindow}=require('./autopost/store.cjs');const {execute,sync,persistPost}=require('./autopost/browser.cjs');
let stopping=false;process.on('SIGINT',()=>{stopping=true;});process.on('SIGTERM',()=>{stopping=true;});
async function cycle(c){const now=Date.now(); const missing=(await c.query("SELECT j.* FROM xc_auto_jobs j WHERE j.status='published' AND j.result_id IS NOT NULL AND (NOT EXISTS(SELECT 1 FROM xc_auto_posts p WHERE p.tweet_id=j.result_id) OR NOT EXISTS(SELECT 1 FROM twitter_tweets t WHERE t.tweet_id=j.result_id)) LIMIT 1")).rows[0];if(missing)try{await persistPost(c,missing,missing.result_id);}catch{}await c.query("UPDATE xc_auto_jobs SET status='cancelled',message='Аккаунт удалён' WHERE status='queued' AND NOT EXISTS(SELECT 1 FROM x_accounts a WHERE a.name=account_name)");await c.query("UPDATE xc_auto_sync SET status='cancelled',message='Аккаунт удалён' WHERE status='queued' AND NOT EXISTS(SELECT 1 FROM x_accounts a WHERE a.name=account_name)");await c.query('UPDATE xc_auto_control SET heartbeat=$1 WHERE id=1',[now]);const control=(await c.query('SELECT paused FROM xc_auto_control WHERE id=1')).rows[0];
 if(!control.paused){const configs=(await c.query("SELECT f.* FROM xc_auto_config f JOIN x_accounts a ON a.name=f.account_name WHERE f.enabled AND a.role='publisher' AND a.status='active' AND f.next_run<=$1",[now])).rows;for(const conf of configs){if(stopping)break;try{await plan(c,conf);}catch{await c.query('UPDATE xc_auto_config SET last_message=$2 WHERE account_name=$1',[conf.account_name,'Цикл ИИ не выполнен. Проверьте провайдера и тест подключения.']);}}}
 if(stopping)return;
 const due=(await c.query(`SELECT j.* FROM xc_auto_jobs j JOIN x_accounts a ON a.name=j.account_name WHERE j.status='queued' AND j.scheduled_at<=$1 AND a.role='publisher' AND a.status='active' AND COALESCE(a.account_busy_until,0)<=$1 AND (j.origin='manual' OR ($2=false AND EXISTS(SELECT 1 FROM xc_auto_config f WHERE f.account_name=j.account_name AND ${eligible}))) ORDER BY j.scheduled_at,j.created_at LIMIT 20`,[now,control.paused,Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Moscow',hour:'numeric',hourCycle:'h23'}).format(now)),Math.floor((now+10800000)/86400000)*86400000-10800000])).rows;
 let job;for(const candidate of due){if(candidate.origin==='manual'){job=candidate;break;}const conf=(await c.query('SELECT * FROM xc_auto_config WHERE account_name=$1',[candidate.account_name])).rows[0];if(!conf?.enabled)continue;const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Moscow',hour:'numeric',hourCycle:'h23'}).format(now));if(!inWindow(hour,conf.start_hour,conf.end_hour))continue;const day=Math.floor((now+10800000)/86400000)*86400000-10800000;const issued=Number((await c.query('SELECT count(*) FROM xc_auto_jobs WHERE account_name=$1 AND attempted AND COALESCE(attempted_at,started_at)>=$2',[candidate.account_name,day])).rows[0].count);if(issued>=conf.daily_limit)continue;job=candidate;break;}
 if(job){if(stopping||!await claim(c,job,now))return;try{if(stopping){await c.query("UPDATE xc_auto_jobs SET status='queued',lease_until=NULL WHERE id=$1 AND status='running' AND NOT attempted",[job.id]);return;}await execute(c,job);}finally{await c.query('UPDATE x_accounts SET account_busy_until=0 WHERE name=$1 AND account_busy_until=$2',[job.account_name,now+600000]);}return;}
 const queued=(await c.query(`SELECT s.* FROM xc_auto_sync s JOIN x_accounts a ON a.name=s.account_name WHERE s.status='queued' AND a.role='publisher' AND a.status='active' AND COALESCE(a.account_busy_until,0)<=$1 ORDER BY s.created_at LIMIT 1`,[now])).rows[0];const periodic=!queued&&(await c.query(`SELECT p.account_name,p.handle AS expected_handle,p.tweet_id FROM xc_auto_posts p WHERE p.updated_at<$1 AND p.posted_at>$2 AND NOT EXISTS(SELECT 1 FROM xc_auto_sync s WHERE s.tweet_id=p.tweet_id AND s.created_at>$1) ORDER BY p.updated_at LIMIT 1`,[now-30*60000,now-30*86400000])).rows[0];const task=queued||periodic;
 if(task){const claimed=await c.query('UPDATE x_accounts SET account_busy_until=$2 WHERE name=$1 AND role=\'publisher\' AND status=\'active\' AND COALESCE(account_busy_until,0)<=$3 RETURNING name',[task.account_name,now+600000,now]);if(!claimed.rowCount)return;try{if(queued)await c.query("UPDATE xc_auto_sync SET status='running' WHERE id=$1",[queued.id]);await sync(c,task.account_name,task.expected_handle,task.tweet_id);if(queued)await c.query("UPDATE xc_auto_sync SET status='done',message='Пост и доступные метрики сохранены',finished_at=$2 WHERE id=$1",[queued.id,Date.now()]);}catch{if(queued)await c.query("UPDATE xc_auto_sync SET status='failed',message='X не вернул пост или сессия не прошла проверку. Старые метрики сохранены.',finished_at=$2 WHERE id=$1",[queued.id,Date.now()]);else await c.query("INSERT INTO xc_auto_sync(id,account_name,expected_handle,tweet_id,status,message,created_at,finished_at) VALUES($1,$2,$3,$4,'failed','Автообновление не выполнено. Старые метрики сохранены.',$5,$5)",[require('node:crypto').randomUUID(),task.account_name,task.expected_handle,task.tweet_id,Date.now()]);}finally{await c.query('UPDATE x_accounts SET account_busy_until=0 WHERE name=$1 AND account_busy_until=$2',[task.account_name,now+600000]);}return;}

}
(async()=>{const c=await connect();try{const locked=(await c.query('SELECT pg_try_advisory_lock(742098531) AS locked')).rows[0].locked;if(!locked)throw Error('busy');
 if((await c.query("SELECT to_regclass('xc_history_runs') AS present")).rows[0].present&&(await c.query("SELECT 1 FROM xc_history_runs WHERE status='running' LIMIT 1")).rowCount){historyCollector=spawn(process.execPath,[path.join(__dirname,'history-collector.cjs')],{cwd:process.cwd(),env:process.env,stdio:['ignore','inherit','inherit','ipc'],windowsHide:true});historyCollector.on('error',()=>console.error('Historical collector could not start.'));}
 if((await c.query("SELECT to_regclass('xc_auto_sources') AS present")).rows[0].present&&(await c.query('SELECT 1 FROM xc_auto_sources WHERE enabled LIMIT 1')).rowCount){const compiled=path.join(__dirname,'../dist/scripts/collect-lists.js');sourceCollector=spawn(process.execPath,fs.existsSync(compiled)?[compiled]:['--import','tsx',path.join(__dirname,'collect-lists.ts')],{cwd:process.cwd(),env:process.env,stdio:['ignore','inherit','inherit','ipc'],windowsHide:true});sourceCollector.on('error',()=>console.error('List collector could not start.'));}
 await c.query("UPDATE xc_auto_jobs SET status=CASE WHEN attempted THEN 'uncertain' ELSE 'queued' END,message=CASE WHEN attempted THEN 'Процесс прерван; проверьте X перед повтором' ELSE 'Восстановлено после перезапуска' END,lease_until=NULL WHERE status='running'");await c.query("UPDATE xc_auto_sync SET status='queued' WHERE status='running'");console.log('Autopost worker running. Ctrl+C stops after current action.');
 while(!stopping){try{await cycle(c);}catch{console.error('Autopost cycle failed. Check database and migrations.');}if(!stopping)await new Promise(r=>setTimeout(r,5000));}
 }finally{if(sourceCollector?.connected)sourceCollector.send({stop:true});if(historyCollector?.connected)historyCollector.send({stop:true});await c.query('SELECT pg_advisory_unlock(742098531)').catch(()=>{});await c.end();}})().catch(()=>{console.error('Unable to start worker. Check migrations/database or an already running worker.');process.exitCode=1;});
