"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, Bot, BrainCircuit, Gauge, Loader2, Network, Radar, RefreshCw, Search, Send, ShieldAlert, Sparkles, Twitter, Users, Zap } from "lucide-react";
import { siteDesign } from "@/lib/siteDesign";

const BACKEND=(process.env.NEXT_PUBLIC_BACKEND_URL||"/fastapi").replace(/\/$/,"");
const MINT_RE=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
type Lookback="1"|"6"|"24"|"72"|"168"|"720"|"all";

type Tweet={id:string;text:string;author:string;likes:number;retweets:number;views:number;timestamp:number|null;isSuspicious:boolean};
type Shiller={handle:string;tweets:number;totalEngagement:number;isBot:boolean;followers:number|null;postsCount:number|null;isVerified:boolean};
type TwitterStats={symbol:string;mint:string;twitterHandle:string|null;totalTweets:number;totalViews:number;totalLikes:number;totalRetweets:number;uniqueMentioners:number;botRisk:"low"|"medium"|"high";botRiskScore:number;anomalyCount:number;topTweets:Tweet[];shillers:Shiller[];lastUpdated:number;collectionStrategy:string;performance:{responseTimeMs:number;cached:boolean};aggregated:{totalEngagement:number;engagementRate:number;verifiedAuthors:number;botSuspectedCount:number;botRatio:number};discovery:{mentions:number;accounts:number;memecoinAccounts:number;firstAccountCreatedAt:number|null;lastDiscoveredAt:number|null}};
type TimelineItem={platform:string;event_type?:string;source_handle:string|null;source_name:string|null;source_url:string|null;text:string;occurred_at:string;metrics:Record<string,unknown>|null};
type SocialTimeline={mint_address:string;mentions:number;platforms:Record<string,number>;origin:TimelineItem|null;timeline:TimelineItem[]};
type Channel={id:number;username:string|null;title:string;participants:number;score:number;calls_count:number;win_rate:number;rug_rate:number;avg_roi:number};
type Market={pair?:{symbol?:string;name?:string;priceUsd?:number;marketCap?:number;liquidityUsd?:number;volumeH24?:number;volumeH6?:number;volumeH1?:number;volumeM5?:number;change24h?:number;changeH1?:number;createdAt?:number|null}};
type AiResult={summary:string;sentiment:{label:string;score:number;confidence:number};dominantIntent:string;coordinationSignals:Array<{type:string;severity:string;confidence:number;explanation:string;evidenceMessageIds:string[]}>;campaignHypothesis:{label:string;confidence:number;likelyOriginators:string[];amplifiers:string[];narrative:string;evidenceMessageIds:string[]};risks:Array<{type:string;severity:string;confidence:number;explanation:string;evidenceMessageIds:string[]}>;reasoningSummary:string[];overallConfidence:number;claims:Array<unknown>;entities:Array<unknown>;relationships:Array<unknown>};
type AiEnvelope={agent:string;available:boolean;status?:string;provider?:string;model?:string;latencyMs?:number;cache?:string;result?:AiResult;error?:string};
type Metric={label:string;value:string;raw?:number|null;note?:string};

type Options={symbol:string;lookback:Lookback;xLimit:number;xVerifiedOnly:boolean;xExcludeSuspicious:boolean;tgLimit:number;tgMinChannelScore:number;tgExplicitCallsOnly:boolean};
const DEFAULT:Options={symbol:"",lookback:"24",xLimit:40,xVerifiedOnly:false,xExcludeSuspicious:true,tgLimit:200,tgMinChannelScore:0,tgExplicitCallsOnly:false};

const num=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const compact=(v:number|null|undefined)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(num(v));
const pct=(v:number|null|undefined)=>Number.isFinite(Number(v))?`${num(v).toFixed(1)}%`:"—";
const score=(v:number|null|undefined)=>Number.isFinite(Number(v))?`${Math.round(num(v))}/100`:"—";
const ago=(v:string|number|null|undefined)=>{if(!v)return"—";let t=typeof v==="number"?v:Date.parse(v);if(!Number.isFinite(t))return"—";if(t<1e12)t*=1000;const m=Math.max(0,Math.round((Date.now()-t)/60000));if(m<60)return`${m}m`;const h=Math.round(m/60);return h<48?`${h}h`:`${Math.round(h/24)}d`};
const ts=(v:string|number|null|undefined)=>{if(!v)return null;let t=typeof v==="number"?v:Date.parse(v);if(!Number.isFinite(t))return null;return t<1e12?t*1000:t};
const avg=(a:number[])=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const median=(a:number[])=>{const x=[...a].sort((p,q)=>p-q);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const lookbackHours=(v:Lookback)=>v==="all"?720:Number(v);
const normalizeText=(v:string)=>v.toLowerCase().replace(/https?:\/\/\S+/g," ").replace(/0x[a-f0-9]+/g," ").replace(/[1-9A-HJ-NP-Za-km-z]{32,44}/g," ").replace(/[^\p{L}\p{N}]+/gu," ").trim().slice(0,220);

function sentiment(texts:string[]){const pos=/\b(bull|bullish|buy|gem|moon|pump|breakout|alpha|early|strong|ape|send|upside|good|great|лонг|покуп|ракета|рост|гем)\b|🚀|🔥|📈|💎/i;const neg=/\b(rug|scam|dump|sell|exit|dead|avoid|warning|bear|rekt|скам|раг|слив|продаж|паден)\b|⚠|📉|☠/i;let p=0,n=0,u=0;texts.forEach(t=>{const a=pos.test(t),b=neg.test(t);a&&!b?p++:b&&!a?n++:u++});const z=p+n+u;if(!z)return{label:"—",p:0,n:0,u:0};return{label:p/z>.52?"BULLISH":n/z>.38?"BEARISH":"MIXED",p:p/z*100,n:n/z*100,u:u/z*100}}
function countSince(times:(number|null)[],mins:number){const cut=Date.now()-mins*60000;return times.filter(v=>v!==null&&v>=cut).length}
function firstTime(items:TimelineItem[]){return Math.min(...items.map(i=>ts(i.occurred_at)).filter((v):v is number=>v!==null),Infinity)}
function safeLag(a:number,b:number){if(!Number.isFinite(a)||!Number.isFinite(b))return"—";const m=Math.round((b-a)/60000);return m===0?"same minute":m>0?`${m}m later`:`${Math.abs(m)}m earlier`}
async function json<T>(url:string,signal?:AbortSignal,init?:RequestInit){const r=await fetch(url,{cache:"no-store",signal,...init});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||d?.error||`HTTP ${r.status}`);return d as T}

export default function SocialIntelligencePanel(){
 const router=useRouter(),params=useSearchParams();const initial=params.get("mint")?.trim()||"";
 const [query,setQuery]=useState(initial),[mint,setMint]=useState(initial),[options,setOptions]=useState<Options>(DEFAULT);
 const [x,setX]=useState<TwitterStats|null>(null),[tg,setTg]=useState<SocialTimeline|null>(null),[channels,setChannels]=useState<Channel[]>([]),[market,setMarket]=useState<Market|null>(null),[ai,setAi]=useState<AiEnvelope|null>(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[warnings,setWarnings]=useState<string[]>([]);const abort=useRef<AbortController|null>(null);

 useEffect(()=>{void json<{items:Channel[]}>(`${BACKEND}/api/v1/telegram/channels?limit=100`).then(v=>setChannels(v.items||[])).catch(()=>{})},[]);
 const run=useCallback(async(next:string)=>{const ca=next.trim();if(!MINT_RE.test(ca)){setError("Введи корректный Solana mint / CA.");return}abort.current?.abort();const c=new AbortController();abort.current=c;setMint(ca);setQuery(ca);setLoading(true);setError(null);setWarnings([]);setAi(null);router.replace(`/trade/analysis/social?mint=${encodeURIComponent(ca)}`,{scroll:false});
  const xp=new URLSearchParams({mint:ca,strategy:"auto",scope:"mentions",limit:String(options.xLimit),excludeSuspicious:String(options.xExcludeSuspicious),verifiedOnly:String(options.xVerifiedOnly)});if(options.symbol)xp.set("symbol",options.symbol.replace(/^\$/,""));if(options.lookback!=="all")xp.set("hours",options.lookback);
  const tp=new URLSearchParams({platform:"telegram",limit:String(options.tgLimit),min_channel_score:String(options.tgMinChannelScore),explicit_calls_only:String(options.tgExplicitCallsOnly)});if(options.lookback!=="all")tp.set("hours",options.lookback);
  const [xr,tr,mr]=await Promise.allSettled([json<TwitterStats>(`/api/trade/dev-twitter?${xp}`,c.signal),json<SocialTimeline>(`${BACKEND}/api/v1/social/token/${encodeURIComponent(ca)}?${tp}`,c.signal),json<Market>(`/api/token-ohlcv?mint=${encodeURIComponent(ca)}`,c.signal)]);if(c.signal.aborted)return;
  const nx=xr.status==="fulfilled"?xr.value:null,nt=tr.status==="fulfilled"?tr.value:null,nm=mr.status==="fulfilled"?mr.value:null;setX(nx);setTg(nt);setMarket(nm);const w:string[]=[];if(!nx)w.push("X недоступен");if(!nt)w.push("Telegram недоступен");if(!nm)w.push("Market недоступен");setWarnings(w);if(!nx&&!nt){setError("Нет данных X и Telegram");setLoading(false);return}
  const tgItems=(nt?.timeline||[]).filter(i=>!i.platform||i.platform.toLowerCase()==="telegram");if(tgItems.length){try{const qa=await json<AiEnvelope>("/api/trade/social-ai",c.signal,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mint:ca,symbol:nx?.symbol||options.symbol,tokenName:nm?.pair?.name,timeline:tgItems})});if(!c.signal.aborted)setAi(qa)}catch(e){if(!c.signal.aborted){setWarnings(v=>[...v,`Qwen: ${e instanceof Error?e.message:"AI недоступен"}`]);setAi({agent:"qwen",available:false,error:e instanceof Error?e.message:"AI недоступен"})}}}
  if(!c.signal.aborted)setLoading(false)
 },[options,router]);
 useEffect(()=>{if(initial&&MINT_RE.test(initial))void run(initial);return()=>abort.current?.abort()},[]);// eslint-disable-line react-hooks/exhaustive-deps

 const derived=useMemo(()=>derive(x,tg,channels,market,ai,options),[x,tg,channels,market,ai,options]);
 const submit=(e:FormEvent)=>{e.preventDefault();void run(query)};
 return <div className="space-y-5" data-tag="trade.social_intelligence.v2">
  <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><Network className="h-5 w-5 text-primary"/><h1 className="text-lg font-semibold text-content">Social Intelligence · X + Telegram + Qwen</h1></div><p className="mt-1 text-xs text-content-muted">Детерминированные social-метрики + второй этап Telegram AI с evidence-based выводами.</p></div>{mint&&<div className="font-mono text-[10px] text-content-faint">{mint.slice(0,8)}…{mint.slice(-7)}</div>}</header>
  <form onSubmit={submit} className="surface-panel rounded-2xl border border-bg-border p-4"><div className="grid gap-3 lg:grid-cols-[1.5fr_.55fr_.55fr_.45fr]">
   <Field label="Solana mint / CA"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-content-faint"/><input value={query} onChange={e=>setQuery(e.target.value)} className={`${siteDesign.controls.inputClassName} pl-9 font-mono`} placeholder="Вставь contract"/></div></Field>
   <Field label="Ticker"><input value={options.symbol} onChange={e=>setOptions(v=>({...v,symbol:e.target.value}))} className={siteDesign.controls.inputClassName} placeholder="BONK"/></Field>
   <Field label="Период"><select value={options.lookback} onChange={e=>setOptions(v=>({...v,lookback:e.target.value as Lookback}))} className={siteDesign.controls.inputClassName}>{[["1","1 час"],["6","6 часов"],["24","24 часа"],["72","3 дня"],["168","7 дней"],["720","30 дней"],["all","Всё"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
   <div className="flex items-end"><button disabled={loading} className={`${siteDesign.controls.primaryActionClassName} w-full`}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Radar className="h-4 w-4"/>} Анализ</button></div>
  </div><details className="mt-3"><summary className="cursor-pointer text-[11px] font-semibold text-content-muted">Фильтры источников</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="X posts"><input type="number" min={10} max={100} value={options.xLimit} onChange={e=>setOptions(v=>({...v,xLimit:Math.max(10,Math.min(100,num(e.target.value))) }))} className={siteDesign.controls.inputClassName}/></Field><Field label="TG signals"><input type="number" min={20} max={500} value={options.tgLimit} onChange={e=>setOptions(v=>({...v,tgLimit:Math.max(20,Math.min(500,num(e.target.value))) }))} className={siteDesign.controls.inputClassName}/></Field><Field label="Min TG score"><input type="number" min={0} max={100} value={options.tgMinChannelScore} onChange={e=>setOptions(v=>({...v,tgMinChannelScore:clamp(num(e.target.value))}))} className={siteDesign.controls.inputClassName}/></Field><Check label="Verified X only" value={options.xVerifiedOnly} set={value=>setOptions(v=>({...v,xVerifiedOnly:value}))}/><Check label="Explicit TG calls" value={options.tgExplicitCallsOnly} set={value=>setOptions(v=>({...v,tgExplicitCallsOnly:value}))}/></div></details>
  </form>
  {error&&<Notice tone="danger" text={error}/>} {warnings.length>0&&<Notice tone="warning" text={warnings.join(" · ")}/>} 
  {(x||tg)&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><Kpi label="Social score" value={score(derived.socialScore)} icon={<Gauge/>}/><Kpi label="X score" value={score(derived.xScore)} icon={<Twitter/>}/><Kpi label="TG score" value={score(derived.tgScore)} icon={<Send/>}/><Kpi label="Organic" value={score(derived.organicScore)} icon={<Sparkles/>}/><Kpi label="Manipulation" value={score(derived.manipulationScore)} icon={<ShieldAlert/>}/><Kpi label="Early signal" value={score(derived.earlySignalScore)} icon={<Zap/>}/><Kpi label="Alpha" value={score(derived.alphaScore)} icon={<Radar/>}/><Kpi label="AI confidence" value={ai?.result?pct(ai.result.overallConfidence*100):"—"} icon={<BrainCircuit/>}/></section>
   <section className="surface-panel rounded-2xl border border-bg-border p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-content">Все параметры</h2><p className="text-[10px] text-content-faint">Поля без исторического источника остаются «—», а не подменяются случайными данными.</p></div><button onClick={()=>void run(mint)} disabled={loading} className={siteDesign.controls.actionButtonClassName}><RefreshCw className="h-4 w-4"/>Обновить</button></div><div className="grid gap-4 xl:grid-cols-2">{derived.groups.map(g=><MetricTable key={g.title} title={g.title} rows={g.rows}/>)}</div></section>
   <AiPanel ai={ai}/><TimelinePanel x={x} tg={tg}/>
  </>}
 </div>
}

function derive(x:TwitterStats|null,tg:SocialTimeline|null,channels:Channel[],market:Market|null,ai:AiEnvelope|null,options:Options){
 const tweets=x?.topTweets||[],tgi=(tg?.timeline||[]).filter(i=>!i.platform||i.platform.toLowerCase()==="telegram"),xt=tweets.map(t=>ts(t.timestamp)),tt=tgi.map(i=>ts(i.occurred_at));
 const x5=countSince(xt,5),x15=countSince(xt,15),x60=countSince(xt,60),tg5=countSince(tt,5),tg15=countSince(tt,15),tg60=countSince(tt,60),hours=Math.max(1,lookbackHours(options.lookback));
 const xs=sentiment(tweets.map(t=>t.text)),tsent=sentiment(tgi.map(t=>t.text));const xMentions=x?.totalTweets||0,tgMentions=tg?.platforms?.telegram||tgi.length;
 const xVelocity=xMentions/hours,tgVelocity=tgMentions/hours;const xAcceleration=x15?clamp((x5/5)/(x15/15)*50):0,tgAcceleration=tg15?clamp((tg5/5)/(tg15/15)*50):0;
 const authorRatio=xMentions?clamp((x?.uniqueMentioners||0)/xMentions*100):0,verifiedRatio=xMentions?clamp((x?.aggregated.verifiedAuthors||0)/Math.max(1,x?.uniqueMentioners||0)*100):0;
 const botRatio=(x?.aggregated.botRatio||0)*100,botRisk=x?.botRiskScore||0;const sh=x?.shillers||[],reach=sh.reduce((s,a)=>s+(a.followers||0),0),influencers=sh.filter(a=>a.isVerified||(a.followers||0)>=10000||(a.totalEngagement||0)>=5000),influencerReach=influencers.reduce((s,a)=>s+(a.followers||0),0),repeat=sh.filter(a=>a.tweets>=2).length,smart=sh.filter(a=>!a.isBot&&(a.isVerified||(a.totalEngagement||0)>=2500||(a.followers||0)>=5000)).length;
 const allTexts=[...tweets.map(t=>t.text),...tgi.map(i=>i.text)].map(normalizeText).filter(t=>t.length>=16),freq=new Map<string,number>();allTexts.forEach(t=>freq.set(t,(freq.get(t)||0)+1));const copied=[...freq.values()].filter(v=>v>1).reduce((s,v)=>s+v,0),copyRatio=allTexts.length?copied/allTexts.length*100:0;
 const latestSusp=tweets.filter(t=>ts(t.timestamp)!==null&&(ts(t.timestamp) as number)>=Date.now()-3600000),botBurst=latestSusp.length?latestSusp.filter(t=>t.isSuspicious).length/latestSusp.length*100:0;
 const tgKeys=new Set(tgi.flatMap(i=>[i.source_handle,i.source_name].filter(Boolean).map(v=>String(v).replace(/^@/,"").toLowerCase())));const relChannels=channels.filter(c=>tgKeys.has(String(c.username||"").replace(/^@/,"").toLowerCase())||tgKeys.has(String(c.title||"").toLowerCase()));const channelScore=relChannels.length?avg(relChannels.map(c=>c.score)):0,winRate=relChannels.length?avg(relChannels.map(c=>c.win_rate))*100:0,rugRate=relChannels.length?avg(relChannels.map(c=>c.rug_rate))*100:0;
 const tgChannels=tgKeys.size,explicitCalls=tgi.filter(i=>Boolean(i.metrics?.explicit_call||i.metrics?.is_explicit_call||String(i.event_type||"").includes("call"))).length;
 const aiResult=ai?.result,coordAi=aiResult?.coordinationSignals?.length||0,highRisks=aiResult?.risks?.filter(r=>r.severity==="high"||r.severity==="critical").length||0,coordScore=clamp(copyRatio*.75+coordAi*11+repeat*3);
 const followerQuality=clamp((100-botRisk)*.45+verifiedRatio*.25+clamp(Math.log10(median(sh.map(a=>a.followers||0))+1)*18)*.3);const paidRisk=clamp(coordScore*.45+botRisk*.25+clamp(repeat*8)*.15+highRisks*8);const organicScore=clamp(100-paidRisk*.72-copyRatio*.18+authorRatio*.22);
 const xScore=clamp((100-botRisk)*.35+authorRatio*.25+clamp(Math.log10((x?.aggregated.totalEngagement||0)+1)*20)*.25+followerQuality*.15);const tgScore=clamp(channelScore*.30+winRate*.20+(100-rugRate)*.20+clamp(tgChannels*7)*.15+clamp(explicitCalls*8)*.15);
 const firstX=Math.min(...xt.filter((v):v is number=>v!==null),Infinity),firstT=firstTime(tgi),crossBoth=Number.isFinite(firstX)&&Number.isFinite(firstT),lag=crossBoth?Math.abs(firstX-firstT)/60000:Infinity,crossScore=crossBoth?clamp(100-Math.min(100,lag/3)+Math.min(xVelocity+tgVelocity,20)*2):0;
 const hype=clamp(avg([xAcceleration,tgAcceleration,clamp((xVelocity+tgVelocity)*10),clamp((x?.aggregated.engagementRate||0)*100)])),fomo=clamp(hype*.55+Math.max(xs.p,tsent.p)*.25+clamp(explicitCalls*7)*.20),manipulationScore=clamp(paidRisk*.7+coordScore*.3);
 const created=ts(market?.pair?.createdAt),firstSocial=Math.min(firstX,firstT),earlyMinutes=created&&Number.isFinite(firstSocial)?Math.max(0,(firstSocial-created)/60000):null,earlySignalScore=earlyMinutes===null?clamp(70-Math.min(60,(xMentions+tgMentions)/10)):clamp(100-earlyMinutes/12);const alphaScore=clamp(earlySignalScore*.35+organicScore*.25+(100-manipulationScore)*.20+crossScore*.20);const socialScore=clamp(xScore*.36+tgScore*.34+organicScore*.15+crossScore*.15);
 const firstXAuthor=tweets.filter(t=>ts(t.timestamp)!==null).sort((a,b)=>num(ts(a.timestamp))-num(ts(b.timestamp)))[0]?.author||"—",firstTg=tg?.origin?.source_handle||tg?.origin?.source_name||tgi.slice().sort((a,b)=>num(ts(a.occurred_at))-num(ts(b.occurred_at)))[0]?.source_handle||"—";
 const narrative=aiResult?.campaignHypothesis?.narrative||"—",campaign=aiResult?.campaignHypothesis?.label||"—";
 const groups:{title:string;rows:Metric[]}[]=[
  {title:"X / Twitter",rows:[m("X score",score(xScore),xScore),m("Mentions",compact(xMentions)),m("Mentions 5m",String(x5),undefined,"sampled posts"),m("Mentions 15m",String(x15)),m("Mentions 1h",String(x60)),m("Mentions / h",xVelocity.toFixed(2)),m("Acceleration",score(xAcceleration),xAcceleration),m("Unique authors",compact(x?.uniqueMentioners)),m("Author diffusion",pct(authorRatio),authorRatio),m("Views",compact(x?.totalViews)),m("Likes",compact(x?.totalLikes)),m("Reposts",compact(x?.totalRetweets)),m("Engagement",compact(x?.aggregated.totalEngagement)),m("Engagement rate",pct((x?.aggregated.engagementRate||0)*100)),m("Verified authors",compact(x?.aggregated.verifiedAuthors)),m("Verified ratio",pct(verifiedRatio)),m("Influencers",String(influencers.length)),m("Potential reach",compact(reach)),m("Influencer reach",compact(influencerReach)),m("Smart accounts",String(smart)),m("Repeat shillers",String(repeat)),m("Bot risk",score(botRisk),botRisk),m("Bot ratio",pct(botRatio),botRatio),m("Bot burst 1h",pct(botBurst),botBurst),m("Anomalies",String(x?.anomalyCount||0)),m("Follower quality",score(followerQuality),followerQuality),m("Sentiment",xs.label),m("Positive",pct(xs.p)),m("Neutral",pct(xs.u)),m("Negative",pct(xs.n)),m("First mover",firstXAuthor),m("First mention",Number.isFinite(firstX)?ago(firstX):"—"),m("Earliest discovered account",x?.discovery.firstAccountCreatedAt?ago(x.discovery.firstAccountCreatedAt):"—")]},
  {title:"Telegram",rows:[m("TG score",score(tgScore),tgScore),m("Mentions",compact(tgMentions)),m("Mentions 5m",String(tg5)),m("Mentions 15m",String(tg15)),m("Mentions 1h",String(tg60)),m("Mentions / h",tgVelocity.toFixed(2)),m("Acceleration",score(tgAcceleration),tgAcceleration),m("Channels",String(tgChannels)),m("Explicit calls",String(explicitCalls)),m("Channel score",score(channelScore),channelScore),m("Historical win rate",pct(winRate)),m("Historical rug rate",pct(rugRate),rugRate),m("Sentiment",aiResult?.sentiment.label||tsent.label),m("AI sentiment score",aiResult?aiResult.sentiment.score.toFixed(2):"—"),m("AI sentiment confidence",aiResult?pct(aiResult.sentiment.confidence*100):"—"),m("Dominant intent",aiResult?.dominantIntent||"—"),m("Top/first source",firstTg),m("First signal",Number.isFinite(firstT)?ago(firstT):"—"),m("AI campaign",campaign),m("AI coordination signals",String(coordAi)),m("AI high risks",String(highRisks)),m("AI overall confidence",aiResult?pct(aiResult.overallConfidence*100):"—")]},
  {title:"Growth / Quality / Manipulation",rows:[m("Hype score",score(hype),hype),m("FOMO score",score(fomo),fomo),m("Organic score",score(organicScore),organicScore),m("Paid promotion risk",score(paidRisk),paidRisk),m("Manipulation score",score(manipulationScore),manipulationScore),m("Coordination score",score(coordScore),coordScore),m("Copy-paste ratio",pct(copyRatio),copyRatio),m("Coordinated AI signals",String(coordAi)),m("Follower quality",score(followerQuality),followerQuality),m("Narrative strength",score(clamp(hype*.45+crossScore*.25+(aiResult?.campaignHypothesis.confidence||0)*30))),m("Narrative",narrative),m("Campaign hypothesis",campaign),m("Peak velocity",Math.max(xVelocity,tgVelocity).toFixed(2)+"/h"),m("Velocity change",score(avg([xAcceleration,tgAcceleration]))),m("Sentiment change","—",undefined,"needs historical sentiment snapshots") ]},
  {title:"Cross-platform / Timing",rows:[m("Cross-platform score",score(crossScore),crossScore),m("Both platforms active",crossBoth?"YES":"NO"),m("TG → X lag",crossBoth&&firstT<=firstX?safeLag(firstT,firstX):"—"),m("X → TG lag",crossBoth&&firstX<firstT?safeLag(firstX,firstT):"—"),m("First X",Number.isFinite(firstX)?ago(firstX):"—"),m("First TG",Number.isFinite(firstT)?ago(firstT):"—"),m("Early signal score",score(earlySignalScore),earlySignalScore),m("Alpha score",score(alphaScore),alphaScore),m("Social score",score(socialScore),socialScore),m("Price → Social", "—",undefined,"requires historical price-event series"),m("Social → Price", "—",undefined,"requires historical price-event series"),m("Price 1h",market?.pair?.changeH1==null?"—":pct(market.pair.changeH1)),m("Price 24h",market?.pair?.change24h==null?"—":pct(market.pair.change24h)),m("Volume 1h",compact(market?.pair?.volumeH1)),m("Volume 24h",compact(market?.pair?.volumeH24)),m("Liquidity",market?.pair?.liquidityUsd==null?"—":`$${compact(market.pair.liquidityUsd)}`)]},
  {title:"AI Agent / Evidence",rows:[m("Agent",ai?.available?`${ai.provider||"qwen"} · ${ai.model||"Qwen"}`:"unavailable"),m("AI latency",ai?.latencyMs?`${Math.round(ai.latencyMs)} ms`:"—"),m("AI cache",ai?.cache||"—"),m("Summary",aiResult?.summary||"—"),m("Claims",String(aiResult?.claims?.length||0)),m("Entities",String(aiResult?.entities?.length||0)),m("Relationships",String(aiResult?.relationships?.length||0)),m("Risks",String(aiResult?.risks?.length||0)),m("Originators",aiResult?.campaignHypothesis.likelyOriginators.join(", ")||"—"),m("Amplifiers",aiResult?.campaignHypothesis.amplifiers.slice(0,6).join(", ")||"—") ]}
 ];return{groups,xScore,tgScore,organicScore,manipulationScore,earlySignalScore,alphaScore,socialScore}
}
const m=(label:string,value:string,raw?:number|null,note?:string):Metric=>({label,value,raw,note});

function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-content-faint">{label}</span>{children}</label>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="flex min-h-10 items-center gap-2 rounded-xl border border-bg-border bg-bg-card px-3 text-xs text-content-muted"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>}
function Notice({tone,text}:{tone:"danger"|"warning";text:string}){return <div className={`flex gap-2 rounded-xl border p-3 text-xs ${tone==="danger"?"border-danger/30 bg-danger/10 text-danger":"border-warning/30 bg-warning/10 text-content-muted"}`}><AlertTriangle className="h-4 w-4 shrink-0"/>{text}</div>}
function Kpi({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="surface-panel rounded-xl border border-bg-border p-3"><div className="flex items-center justify-between text-content-faint"><span className="text-[9px] uppercase tracking-wider">{label}</span><span className="[&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span></div><div className="mt-2 font-mono text-lg font-bold text-content">{value}</div></div>}
function MetricTable({title,rows}:{title:string;rows:Metric[]}){return <div className="overflow-hidden rounded-xl border border-bg-border"><div className="border-b border-bg-border bg-bg-elevated/60 px-3 py-2 text-xs font-semibold text-content">{title}</div><div className="divide-y divide-bg-border">{rows.map(r=><div key={r.label} className="grid grid-cols-[minmax(0,1fr)_minmax(90px,.8fr)] gap-3 px-3 py-2 text-[11px]"><div><div className="text-content-muted">{r.label}</div>{r.note&&<div className="mt-0.5 text-[9px] text-content-faint">{r.note}</div>}</div><div className="break-words text-right font-mono font-semibold text-content">{r.value}</div></div>)}</div></div>}
function AiPanel({ai}:{ai:AiEnvelope|null}){const r=ai?.result;return <section className="surface-panel rounded-2xl border border-bg-border p-4"><div className="mb-3 flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-primary"/><h2 className="text-sm font-semibold text-content">Qwen AI · Telegram second-stage analysis</h2></div>{!ai?<div className="text-xs text-content-faint">AI запускается после получения Telegram сообщений.</div>:!r?<div className="text-xs text-warning">Qwen недоступен: {ai.error||"нет результата"}</div>:<div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm leading-6 text-content-soft">{r.summary}</p><div className="mt-3 rounded-xl border border-bg-border bg-bg-card p-3"><div className="text-[10px] uppercase tracking-wider text-content-faint">Campaign narrative</div><div className="mt-1 text-xs leading-5 text-content-muted">{r.campaignHypothesis.narrative||"—"}</div></div></div><div className="space-y-2">{r.reasoningSummary.map((v,i)=><div key={i} className="rounded-lg border border-bg-border bg-bg-elevated/50 px-3 py-2 text-xs text-content-muted">{v}</div>)}</div></div>}</section>}
function TimelinePanel({x,tg}:{x:TwitterStats|null;tg:SocialTimeline|null}){const items=useMemo(()=>{const a:TimelineItem[]=[...(tg?.timeline||[])];for(const t of x?.topTweets||[])a.push({platform:"x",source_handle:t.author,source_name:null,source_url:null,text:t.text,occurred_at:t.timestamp?new Date(t.timestamp).toISOString():"",metrics:{likes:t.likes,retweets:t.retweets,views:t.views}});return a.sort((p,q)=>num(ts(p.occurred_at))-num(ts(q.occurred_at))).slice(0,80)},[x,tg]);return <section className="surface-panel rounded-2xl border border-bg-border p-4"><h2 className="text-sm font-semibold text-content">Signal timeline · TG → X → Hype</h2><div className="mt-3 space-y-2">{items.length?items.map((i,n)=><div key={`${n}-${i.source_handle}`} className="grid grid-cols-[70px_110px_1fr] gap-2 rounded-xl border border-bg-border bg-bg-card/50 p-2 text-[10px]"><div className="font-mono text-content-faint">{i.occurred_at?new Date(i.occurred_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"—"}</div><div className="font-semibold text-content">{i.platform.toUpperCase()} · {i.source_handle||i.source_name||"source"}</div><div className="line-clamp-2 text-content-muted">{i.text}</div></div>):<div className="text-xs text-content-faint">Нет timestamped сигналов.</div>}</div></section>}
