"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, BrainCircuit, Gauge, Loader2, Network, Radar, RefreshCw, Search, Send, ShieldAlert, Sparkles, TrendingUp, Twitter, Zap } from "lucide-react";
import { siteDesign } from "@/lib/siteDesign";

const BACKEND=(process.env.NEXT_PUBLIC_BACKEND_URL||"/fastapi").replace(/\/$/,"");
const MINT_RE=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
const IMPULSE_WINDOW=5*60_000, IMPULSE_PCT=10;
type Lookback="1"|"6"|"24"|"72"|"168"|"720"|"all";
type Options={symbol:string;lookback:Lookback;xLimit:number;xVerifiedOnly:boolean;xExcludeSuspicious:boolean;tgLimit:number;tgMinChannelScore:number;tgExplicitCallsOnly:boolean};
type Timeline={platform:string;event_type?:string;source_handle:string|null;source_name:string|null;source_url:string|null;text:string;occurred_at:string;metrics:Record<string,unknown>|null};
type Metric={label:string;value:string;note?:string};
type PriceSocial={socialSpikeTime:number|null;reaction5:number|null;reaction15:number|null;reaction60:number|null;maxUpside:number|null;maxDrawdown:number|null;impulseTime:number|null;impulseChange:number|null;leadLagMinutes:number|null;leadDirection:string;leadLagConfidence:number|null;tradeCount:number};
const DEFAULT:Options={symbol:"",lookback:"24",xLimit:40,xVerifiedOnly:false,xExcludeSuspicious:true,tgLimit:200,tgMinChannelScore:0,tgExplicitCallsOnly:false};
const n=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const compact=(v:unknown)=>new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(n(v));
const pct=(v:unknown)=>Number.isFinite(Number(v))?`${n(v).toFixed(1)}%`:"—";
const signed=(v:unknown)=>Number.isFinite(Number(v))?`${n(v)>=0?"+":""}${n(v).toFixed(1)}%`:"—";
const score=(v:unknown)=>Number.isFinite(Number(v))?`${Math.round(n(v))}/100`:"—";
const money=(v:unknown)=>Number.isFinite(Number(v))?`$${compact(v)}`:"—";
const ts=(v:unknown)=>{if(v==null||v==="")return null;let t=typeof v==="number"?v:Date.parse(String(v));if(!Number.isFinite(t))return null;return t<1e12?t*1000:t};
const ago=(v:unknown)=>{const t=ts(v);if(t==null)return"—";const m=Math.max(0,Math.round((Date.now()-t)/60_000));return m<60?`${m}m`:m<2880?`${Math.round(m/60)}h`:`${Math.round(m/1440)}d`};
const avg=(a:number[])=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const median=(a:number[])=>{const x=[...a].sort((p,q)=>p-q);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const norm=(s:string)=>s.toLowerCase().replace(/https?:\/\/\S+/g," ").replace(/[1-9A-HJ-NP-Za-km-z]{32,44}/g," ").replace(/[^\p{L}\p{N}]+/gu," ").trim().slice(0,220);
const countSince=(a:Array<number|null>,m:number)=>{const c=Date.now()-m*60_000;return a.filter(v=>v!=null&&v>=c).length};
const growth=(cur:number,prev:number)=>prev<=0?(cur>0?100:null):(cur-prev)/prev*100;
function uniqueWindow<T>(rows:T[],time:(r:T)=>number|null,key:(r:T)=>unknown,from:number,to:number){const now=Date.now(),a=now-from*60_000,b=now-to*60_000,s=new Set<string>();for(const r of rows){const t=time(r),k=key(r);if(t!=null&&k&&t>=a&&t<b)s.add(String(k).toLowerCase())}return s.size}
function sent(texts:string[]){const p=/\b(bull|bullish|buy|gem|moon|pump|breakout|alpha|early|strong|ape|send|upside|good|great|лонг|покуп|ракета|рост|гем)\b|🚀|🔥|📈|💎/i, q=/\b(rug|scam|dump|sell|exit|dead|avoid|warning|bear|rekt|скам|раг|слив|продаж|паден)\b|⚠|📉|☠/i;let a=0,b=0,u=0;for(const t of texts){const x=p.test(t),y=q.test(t);x&&!y?a++:y&&!x?b++:u++}const z=a+b+u;return z?{label:a/z>.52?"BULLISH":b/z>.38?"BEARISH":"MIXED",p:a/z*100,n:b/z*100,u:u/z*100}:{label:"—",p:0,n:0,u:0}}
function sentDelta(rows:Array<{t:number|null;text:string}>){const a=rows.filter((r):r is {t:number;text:string}=>r.t!=null).sort((x,y)=>x.t-y.t);if(a.length<4)return null;const m=Math.floor(a.length/2);return sent(a.slice(m).map(v=>v.text)).p-sent(a.slice(0,m).map(v=>v.text)).p}
function densest(times:number[],window=5*60_000){const a=[...times].sort((x,y)=>x-y);if(!a.length)return null;let bs=0,be=0,e=0;for(let s=0;s<a.length;s++){if(e<s)e=s;while(e+1<a.length&&a[e+1]-a[s]<=window)e++;if(e-s>be-bs){bs=s;be=e}}return a[Math.floor((bs+be)/2)]}
function nearest(trades:Array<{time:number;price:number}>,target:number,tol:number){let best:null|{time:number;price:number}=null;for(const x of trades){const d=Math.abs(x.time-target);if(d<=tol&&(!best||d<Math.abs(best.time-target)))best=x}return best}
function chg(a:{price:number}|null,b:{price:number}|null){return a&&b&&a.price>0?(b.price-a.price)/a.price*100:null}
function impulse(trades:Array<{time:number;price:number}>,target:number|null){const c:Array<{time:number;change:number}>=[];for(const x of trades){if(target!=null&&Math.abs(x.time-target)>6*3600_000)continue;const b=nearest(trades,x.time-IMPULSE_WINDOW,Math.max(120_000,IMPULSE_WINDOW/2));if(!b)continue;const d=(x.price-b.price)/b.price*100;if(Math.abs(d)>=IMPULSE_PCT)c.push({time:x.time,change:d})}if(!c.length)return null;return target==null?c[0]:c.sort((a,b)=>Math.abs(a.time-target)-Math.abs(b.time-target))[0]}
async function json<T>(url:string,signal?:AbortSignal,init?:RequestInit){const r=await fetch(url,{cache:"no-store",signal,...init});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||d?.error||`HTTP ${r.status}`);return d as T}
async function chainStream(mint:string,signal:AbortSignal){const r=await fetch(`/api/trade/analyze-stream?mint=${encodeURIComponent(mint)}`,{cache:"no-store",signal});if(!r.ok||!r.body)throw new Error(`analyze-stream HTTP ${r.status}`);const rd=r.body.getReader(),dec=new TextDecoder();let buf="",fin:any=null;for(;;){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});const lines=buf.split("\n");buf=lines.pop()||"";for(const line of lines){if(!line.trim())continue;let e:any;try{e=JSON.parse(line)}catch{continue}if(e.type==="error")throw new Error(e.message||"on-chain analysis failed");if(e.type==="final"){delete e.type;fin=e}}}return fin}
const mm=(label:string,value:string,note?:string):Metric=>({label,value,note});

export default function SocialIntelligencePanel(){
 const router=useRouter(),params=useSearchParams(),initial=params.get("mint")?.trim()||"";
 const [query,setQuery]=useState(initial),[mint,setMint]=useState(initial),[options,setOptions]=useState<Options>(DEFAULT);
 const [x,setX]=useState<any>(null),[tg,setTg]=useState<any>(null),[market,setMarket]=useState<any>(null),[chain,setChain]=useState<any>(null),[ai,setAi]=useState<any>(null),[channels,setChannels]=useState<any[]>([]);
 const [loading,setLoading]=useState(false),[chainLoading,setChainLoading]=useState(false),[error,setError]=useState<string|null>(null),[warnings,setWarnings]=useState<string[]>([]);const abort=useRef<AbortController|null>(null);
 useEffect(()=>{void json<any>(`${BACKEND}/api/v1/telegram/channels?limit=100`).then(v=>setChannels(v.items||[])).catch(()=>{})},[]);
 const run=useCallback(async(next:string)=>{const ca=next.trim();if(!MINT_RE.test(ca)){setError("Введи корректный Solana mint / CA.");return}abort.current?.abort();const c=new AbortController();abort.current=c;setMint(ca);setQuery(ca);setLoading(true);setChainLoading(true);setError(null);setWarnings([]);setAi(null);setChain(null);router.replace(`/trade/analysis/social?mint=${encodeURIComponent(ca)}`,{scroll:false});
  const xp=new URLSearchParams({mint:ca,strategy:"auto",scope:"mentions",limit:String(options.xLimit),excludeSuspicious:String(options.xExcludeSuspicious),verifiedOnly:String(options.xVerifiedOnly)});if(options.symbol)xp.set("symbol",options.symbol.replace(/^\$/,""));if(options.lookback!=="all")xp.set("hours",options.lookback);
  const tp=new URLSearchParams({platform:"telegram",limit:String(options.tgLimit),min_channel_score:String(options.tgMinChannelScore),explicit_calls_only:String(options.tgExplicitCallsOnly)});if(options.lookback!=="all")tp.set("hours",options.lookback);
  void chainStream(ca,c.signal).then(v=>{if(!c.signal.aborted)setChain(v)}).catch(e=>{if(!c.signal.aborted)setWarnings(v=>[...v.filter(s=>!s.startsWith("Trade history:")),`Trade history: ${e instanceof Error?e.message:"недоступна"}`])}).finally(()=>{if(!c.signal.aborted)setChainLoading(false)});
  const [xr,tr,mr]=await Promise.allSettled([json<any>(`/api/trade/dev-twitter?${xp}`,c.signal),json<any>(`${BACKEND}/api/v1/social/token/${encodeURIComponent(ca)}?${tp}`,c.signal),json<any>(`/api/token-ohlcv?mint=${encodeURIComponent(ca)}`,c.signal)]);if(c.signal.aborted)return;const nx=xr.status==="fulfilled"?xr.value:null,nt=tr.status==="fulfilled"?tr.value:null,nm=mr.status==="fulfilled"?mr.value:null;setX(nx);setTg(nt);setMarket(nm);const w:string[]=[];if(!nx)w.push("X недоступен");if(!nt)w.push("Telegram недоступен");if(!nm)w.push("Market недоступен");setWarnings(v=>[...w,...v.filter(s=>s.startsWith("Trade history:"))]);if(!nx&&!nt){setError("Нет данных X и Telegram");setLoading(false);return}
  const ti=(nt?.timeline||[]).filter((i:Timeline)=>!i.platform||i.platform.toLowerCase()==="telegram");if(ti.length){try{const q=await json<any>("/api/trade/social-ai",c.signal,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mint:ca,symbol:nx?.symbol||options.symbol,tokenName:nm?.pair?.name,timeline:ti})});if(!c.signal.aborted)setAi(q)}catch(e){if(!c.signal.aborted){const m=e instanceof Error?e.message:"AI недоступен";setWarnings(v=>[...v,`Qwen: ${m}`]);setAi({agent:"qwen",available:false,error:m})}}}if(!c.signal.aborted)setLoading(false)
 },[options,router]);
 useEffect(()=>{if(initial&&MINT_RE.test(initial))void run(initial);return()=>abort.current?.abort()},[]);
 const d=useMemo(()=>derive(x,tg,market,chain,ai,channels,options),[x,tg,market,chain,ai,channels,options]);
 const submit=(e:FormEvent)=>{e.preventDefault();void run(query)};
 return <div className="space-y-5" data-tag="trade.social_intelligence.v4">
  <header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><Network className="h-5 w-5 text-primary"/><h1 className="text-lg font-semibold text-content">Social Intelligence · X + Telegram + Qwen</h1></div><p className="mt-1 text-xs text-content-muted">Social-метрики, Telegram AI и Price ↔ Social по реальным on-chain timestamps.</p></div>{mint&&<div className="font-mono text-[10px] text-content-faint">{mint.slice(0,8)}…{mint.slice(-7)}</div>}</header>
  <form onSubmit={submit} className="surface-panel rounded-2xl border border-bg-border p-4"><div className="grid gap-3 lg:grid-cols-[1.5fr_.55fr_.55fr_.45fr]"><Field label="Solana mint / CA"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-content-faint"/><input value={query} onChange={e=>setQuery(e.target.value)} className={`${siteDesign.controls.inputClassName} pl-9 font-mono`} placeholder="Вставь contract"/></div></Field><Field label="Ticker"><input value={options.symbol} onChange={e=>setOptions(v=>({...v,symbol:e.target.value}))} className={siteDesign.controls.inputClassName} placeholder="BONK"/></Field><Field label="Период"><select value={options.lookback} onChange={e=>setOptions(v=>({...v,lookback:e.target.value as Lookback}))} className={siteDesign.controls.inputClassName}>{[["1","1 час"],["6","6 часов"],["24","24 часа"],["72","3 дня"],["168","7 дней"],["720","30 дней"],["all","Всё"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div className="flex items-end"><button disabled={loading} className={`${siteDesign.controls.primaryActionClassName} w-full`}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Radar className="h-4 w-4"/>} Анализ</button></div></div>
   <details className="mt-3"><summary className="cursor-pointer text-[11px] font-semibold text-content-muted">Фильтры источников</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label="X posts"><input type="number" min={10} max={100} value={options.xLimit} onChange={e=>setOptions(v=>({...v,xLimit:Math.max(10,Math.min(100,n(e.target.value)))}))} className={siteDesign.controls.inputClassName}/></Field><Field label="TG signals"><input type="number" min={20} max={500} value={options.tgLimit} onChange={e=>setOptions(v=>({...v,tgLimit:Math.max(20,Math.min(500,n(e.target.value)))}))} className={siteDesign.controls.inputClassName}/></Field><Field label="Min TG score"><input type="number" min={0} max={100} value={options.tgMinChannelScore} onChange={e=>setOptions(v=>({...v,tgMinChannelScore:clamp(n(e.target.value))}))} className={siteDesign.controls.inputClassName}/></Field><Check label="Verified X only" value={options.xVerifiedOnly} set={z=>setOptions(v=>({...v,xVerifiedOnly:z}))}/><Check label="Exclude suspicious X" value={options.xExcludeSuspicious} set={z=>setOptions(v=>({...v,xExcludeSuspicious:z}))}/><Check label="Explicit TG calls" value={options.tgExplicitCallsOnly} set={z=>setOptions(v=>({...v,tgExplicitCallsOnly:z}))}/></div></details>
  </form>
  {error&&<Notice tone="danger" text={error}/>} {warnings.length>0&&<Notice tone="warning" text={warnings.join(" · ")}/>} 
  {(x||tg)&&<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5 xl:grid-cols-9"><Kpi label="Social score" value={score(d.socialScore)} icon={<Gauge/>}/><Kpi label="X score" value={score(d.xScore)} icon={<Twitter/>}/><Kpi label="TG score" value={score(d.tgScore)} icon={<Send/>}/><Kpi label="Organic" value={score(d.organic)} icon={<Sparkles/>}/><Kpi label="Manipulation" value={score(d.manipulation)} icon={<ShieldAlert/>}/><Kpi label="Social risk" value={score(d.socialRisk)} icon={<ShieldAlert/>}/><Kpi label="Early" value={score(d.early)} icon={<Zap/>}/><Kpi label="Alpha" value={score(d.alpha)} icon={<Radar/>}/><Kpi label="AI confidence" value={ai?.result?pct(ai.result.overallConfidence*100):"—"} icon={<BrainCircuit/>}/></section><PricePanel p={d.price} loading={chainLoading}/><section className="surface-panel rounded-2xl border border-bg-border p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-semibold text-content">Все параметры</h2><p className="text-[10px] text-content-faint">Поля без достаточной выборки остаются «—» — случайные значения не используются.</p></div><button type="button" onClick={()=>void run(mint)} disabled={loading} className={siteDesign.controls.actionButtonClassName}><RefreshCw className="h-4 w-4"/>Обновить</button></div><div className="grid gap-4 xl:grid-cols-2">{d.groups.map((g:{title:string;rows:Metric[]})=><Table key={g.title} title={g.title} rows={g.rows}/>)}</div></section><Ai ai={ai}/><TimelinePanel x={x} tg={tg} impulseAt={d.price.impulseTime} impulseChange={d.price.impulseChange}/></>}
 </div>
}

function derive(x:any,tg:any,market:any,chain:any,ai:any,channels:any[],o:Options){
 const xt=x?.topTweets||[],ti:Timeline[]=(tg?.timeline||[]).filter((i:Timeline)=>!i.platform||i.platform.toLowerCase()==="telegram"),xTimes=xt.map((t:any)=>ts(t.timestamp)),tTimes=ti.map(i=>ts(i.occurred_at)),hours=Math.max(1,o.lookback==="all"?720:Number(o.lookback));
 const xm=x?.totalTweets||0,tm=tg?.platforms?.telegram||ti.length,xv=xm/hours,tv=tm/hours,x5=countSince(xTimes,5),x15=countSince(xTimes,15),x60=countSince(xTimes,60),x6=countSince(xTimes,360),x24=countSince(xTimes,1440),t5=countSince(tTimes,5),t15=countSince(tTimes,15),t60=countSince(tTimes,60),t6=countSince(tTimes,360),t24=countSince(tTimes,1440),xa=x15?clamp((x5/5)/(x15/15)*50):0,ta=t15?clamp((t5/5)/(t15/15)*50):0;
 const xA6=uniqueWindow<any>(xt,t=>ts(t.timestamp),t=>t.author,360,0),xAp=uniqueWindow<any>(xt,t=>ts(t.timestamp),t=>t.author,720,360),xA24=uniqueWindow<any>(xt,t=>ts(t.timestamp),t=>t.author,1440,0),tC6=uniqueWindow<Timeline>(ti,i=>ts(i.occurred_at),i=>i.source_handle||i.source_name,360,0),tCp=uniqueWindow<Timeline>(ti,i=>ts(i.occurred_at),i=>i.source_handle||i.source_name,720,360),tC24=uniqueWindow<Timeline>(ti,i=>ts(i.occurred_at),i=>i.source_handle||i.source_name,1440,0);
 const xs=sent(xt.map((t:any)=>t.text)),tts=sent(ti.map(i=>i.text)),xsd=sentDelta(xt.map((t:any)=>({t:ts(t.timestamp),text:t.text}))),tsd=sentDelta(ti.map(i=>({t:ts(i.occurred_at),text:i.text}))),authorRatio=xm?clamp((x?.uniqueMentioners||0)/xm*100):0,vr=xm?clamp((x?.aggregated?.verifiedAuthors||0)/Math.max(1,x?.uniqueMentioners||0)*100):0,bot=(x?.aggregated?.botRatio||0)*100,botRisk=x?.botRiskScore||0,sh=x?.shillers||[],reach=sh.reduce((s:number,a:any)=>s+(a.followers||0),0),infl=sh.filter((a:any)=>a.isVerified||(a.followers||0)>=10000||a.totalEngagement>=5000),inflReach=infl.reduce((s:number,a:any)=>s+(a.followers||0),0),repeat=sh.filter((a:any)=>a.tweets>=2).length,smart=sh.filter((a:any)=>!a.isBot&&(a.isVerified||a.totalEngagement>=2500||(a.followers||0)>=5000)).length;
 const texts=[...xt.map((t:any)=>t.text),...ti.map(i=>i.text)].map(norm).filter(t=>t.length>=16),freq=new Map<string,number>();texts.forEach(t=>freq.set(t,(freq.get(t)||0)+1));const copy=texts.length?[...freq.values()].filter(v=>v>1).reduce((s,v)=>s+v,0)/texts.length*100:0,lastX=xt.filter((t:any)=>{const z=ts(t.timestamp);return z!=null&&z>=Date.now()-3600_000}),burst=lastX.length?lastX.filter((t:any)=>t.isSuspicious).length/lastX.length*100:0;
 const keys=new Set(ti.flatMap(i=>[i.source_handle,i.source_name].filter(Boolean).map(v=>String(v).replace(/^@/,"").toLowerCase()))),rel=channels.filter(c=>keys.has(String(c.username||"").replace(/^@/,"").toLowerCase())||keys.has(String(c.title||"").toLowerCase())),cs=rel.length?avg(rel.map(c=>n(c.score))):0,win=rel.length?avg(rel.map(c=>n(c.win_rate)))*100:0,rug=rel.length?avg(rel.map(c=>n(c.rug_rate)))*100:0,calls=ti.filter(i=>Boolean(i.metrics?.explicit_call||i.metrics?.is_explicit_call)||String(i.event_type||"").includes("call")).length;
 const ar=ai?.result,coord=ar?.coordinationSignals?.length||0,high=ar?.risks?.filter((r:any)=>r.severity==="high"||r.severity==="critical").length||0,coordScore=clamp(copy*.75+coord*11+repeat*3),fq=clamp((100-botRisk)*.45+vr*.25+clamp(Math.log10(median(sh.map((a:any)=>a.followers||0))+1)*18)*.3),paid=clamp(coordScore*.45+botRisk*.25+clamp(repeat*8)*.15+high*8),organic=clamp(100-paid*.72-copy*.18+authorRatio*.22),xScore=clamp((100-botRisk)*.35+authorRatio*.25+clamp(Math.log10((x?.aggregated?.totalEngagement||0)+1)*20)*.25+fq*.15),tgScore=clamp(cs*.3+win*.2+(100-rug)*.2+clamp(keys.size*7)*.15+clamp(calls*8)*.15);
 const fx=Math.min(...xTimes.filter((v:any):v is number=>v!=null),Infinity),ft=Math.min(...tTimes.filter((v:any):v is number=>v!=null),Infinity),both=Number.isFinite(fx)&&Number.isFinite(ft),lag=both?Math.abs(fx-ft)/60_000:Infinity,cross=both?clamp(100-Math.min(100,lag/3)+Math.min(xv+tv,20)*2):0,hype=clamp(avg([xa,ta,clamp((xv+tv)*10),clamp((x?.aggregated?.engagementRate||0)*100)])),fomo=clamp(hype*.55+Math.max(xs.p,tts.p)*.25+clamp(calls*7)*.2),manipulation=clamp(paid*.7+coordScore*.3),socialRisk=clamp(manipulation*.4+botRisk*.24+rug*.14+(100-organic)*.12+Math.min(100,high*18)*.1),riskLevel=socialRisk>=70?"HIGH":socialRisk>=40?"MEDIUM":"LOW";
 const created=ts(market?.pair?.createdAt),first=Math.min(fx,ft),earlyMin=created&&Number.isFinite(first)?Math.max(0,(first-created)/60_000):null,early=earlyMin==null?clamp(70-Math.min(60,(xm+tm)/10)):clamp(100-earlyMin/12),alpha=clamp(early*.35+organic*.25+(100-manipulation)*.2+cross*.2),socialScore=clamp(xScore*.36+tgScore*.34+organic*.15+cross*.15);
 const ev=[...xTimes.filter((v:any):v is number=>v!=null),...tTimes.filter((v:any):v is number=>v!=null)],spike=densest(ev),trades=(chain?.trades||[]).map((t:any)=>({time:ts(t.ts),price:n(t.p,NaN)})).filter((t:any)=>t.time!=null&&Number.isFinite(t.price)&&t.price>0).sort((a:any,b:any)=>a.time-b.time) as Array<{time:number;price:number}>,imp=impulse(trades,spike),p0=spike==null?null:nearest(trades,spike,5*60_000),p5=spike==null?null:nearest(trades,spike+5*60_000,5*60_000),p15=spike==null?null:nearest(trades,spike+15*60_000,5*60_000),p60=spike==null?null:nearest(trades,spike+60*60_000,10*60_000),r5=chg(p0,p5),r15=chg(p0,p15),r60=chg(p0,p60),one=spike==null?[]:trades.filter(t=>t.time>=spike&&t.time<=spike+3600_000),mx=one.length?Math.max(...one.map(t=>t.price)):null,mn=one.length?Math.min(...one.map(t=>t.price)):null,up=p0&&mx!=null?(mx-p0.price)/p0.price*100:null,dd=p0&&mn!=null?(mn-p0.price)/p0.price*100:null,ll=spike!=null&&imp?(imp.time-spike)/60_000:null,dir=ll==null?"—":Math.abs(ll)<=2?"SYNC":ll>0?"SOCIAL → PRICE":"PRICE → SOCIAL",conf=ll==null?null:clamp(35+Math.min(35,ev.length*1.5)+Math.min(30,trades.length/20)),price:PriceSocial={socialSpikeTime:spike,reaction5:r5,reaction15:r15,reaction60:r60,maxUpside:up,maxDrawdown:dd,impulseTime:imp?.time??null,impulseChange:imp?.change??null,leadLagMinutes:ll,leadDirection:dir,leadLagConfidence:conf,tradeCount:trades.length};
 const firstX=xt.filter((t:any)=>ts(t.timestamp)!=null).sort((a:any,b:any)=>n(ts(a.timestamp))-n(ts(b.timestamp)))[0]?.author||"—",firstT=tg?.origin?.source_handle||tg?.origin?.source_name||ti.slice().sort((a,b)=>n(ts(a.occurred_at))-n(ts(b.occurred_at)))[0]?.source_handle||"—",sd=[xsd,tsd].filter((v):v is number=>v!=null),sdAll=sd.length?avg(sd):null,narr=ar?.campaignHypothesis?.narrative||"—",campaign=ar?.campaignHypothesis?.label||"—";
 const groups=[
  {title:"X / Twitter",rows:[mm("X score",score(xScore)),mm("Mentions",compact(xm)),mm("Mentions 5m",String(x5),"sampled top posts"),mm("Mentions 15m",String(x15),"sampled top posts"),mm("Mentions 1h",String(x60),"sampled top posts"),mm("Mentions 6h",String(x6),"sampled top posts"),mm("Mentions 24h",String(x24),"sampled top posts"),mm("Mentions / h",xv.toFixed(2)),mm("Acceleration",score(xa)),mm("Unique authors",compact(x?.uniqueMentioners)),mm("Unique authors 6h",String(xA6),"sampled top posts"),mm("Unique authors 24h",String(xA24),"sampled top posts"),mm("Author growth 6h",signed(growth(xA6,xAp)),"vs previous 6h"),mm("Author diffusion",pct(authorRatio)),mm("Views",compact(x?.totalViews)),mm("Likes",compact(x?.totalLikes)),mm("Reposts",compact(x?.totalRetweets)),mm("Engagement",compact(x?.aggregated?.totalEngagement)),mm("Engagement rate",pct((x?.aggregated?.engagementRate||0)*100)),mm("Verified authors",compact(x?.aggregated?.verifiedAuthors)),mm("Verified ratio",pct(vr)),mm("Influencers",String(infl.length)),mm("Potential reach",compact(reach)),mm("Influencer reach",compact(inflReach)),mm("Smart accounts",String(smart)),mm("Repeat shillers",String(repeat)),mm("Bot risk",score(botRisk)),mm("Bot ratio",pct(bot)),mm("Bot burst 1h",pct(burst)),mm("Anomalies",String(x?.anomalyCount||0)),mm("Follower quality",score(fq)),mm("Sentiment",xs.label),mm("Positive",pct(xs.p)),mm("Neutral",pct(xs.u)),mm("Negative",pct(xs.n)),mm("Sentiment change",signed(xsd)),mm("First mover",firstX),mm("First mention",Number.isFinite(fx)?ago(fx):"—"),mm("Account age","—","X collector does not expose account creation date")]},
  {title:"Telegram",rows:[mm("TG score",score(tgScore)),mm("Mentions",compact(tm)),mm("Mentions 5m",String(t5)),mm("Mentions 15m",String(t15)),mm("Mentions 1h",String(t60)),mm("Mentions 6h",String(t6)),mm("Mentions 24h",String(t24)),mm("Mentions / h",tv.toFixed(2)),mm("Acceleration",score(ta)),mm("Channels",String(keys.size)),mm("Channels 6h",String(tC6)),mm("Channels 24h",String(tC24)),mm("Channel growth 6h",signed(growth(tC6,tCp)),"vs previous 6h"),mm("Explicit calls",String(calls)),mm("Channel score",score(cs)),mm("Historical win rate",pct(win)),mm("Historical rug rate",pct(rug)),mm("Sentiment",ar?.sentiment?.label||tts.label),mm("AI sentiment score",ar?.sentiment?n(ar.sentiment.score).toFixed(2):"—"),mm("AI sentiment confidence",ar?.sentiment?pct(n(ar.sentiment.confidence)*100):"—"),mm("Window sentiment change",signed(tsd)),mm("Dominant intent",ar?.dominantIntent||"—"),mm("Top/first source",firstT),mm("First signal",Number.isFinite(ft)?ago(ft):"—"),mm("AI campaign",campaign),mm("AI coordination signals",String(coord)),mm("AI high risks",String(high)),mm("AI overall confidence",ar?pct(n(ar.overallConfidence)*100):"—")]},
  {title:"Growth / Quality / Manipulation",rows:[mm("Hype score",score(hype)),mm("FOMO score",score(fomo)),mm("Organic score",score(organic)),mm("Paid promotion risk",score(paid)),mm("Manipulation score",score(manipulation)),mm("Social risk",score(socialRisk)),mm("Social risk level",riskLevel),mm("Coordination score",score(coordScore)),mm("Copy-paste ratio",pct(copy)),mm("Follower quality",score(fq)),mm("Narrative strength",score(clamp(hype*.45+cross*.25+n(ar?.campaignHypothesis?.confidence)*30))),mm("Narrative",narr),mm("Campaign hypothesis",campaign),mm("Peak velocity",`${Math.max(xv,tv).toFixed(2)}/h`),mm("Velocity change",score(avg([xa,ta]))),mm("Sentiment change",signed(sdAll),"positive-share change inside window")]},
  {title:"Cross-platform / Timing",rows:[mm("Cross-platform score",score(cross)),mm("Both platforms active",both?"YES":"NO"),mm("TG → X lag",both&&ft<=fx?`${Math.round((fx-ft)/60_000)}m`:"—"),mm("X → TG lag",both&&fx<ft?`${Math.round((ft-fx)/60_000)}m`:"—"),mm("First X",Number.isFinite(fx)?ago(fx):"—"),mm("First TG",Number.isFinite(ft)?ago(ft):"—"),mm("Social spike",spike==null?"—":ago(spike),"densest 5m window"),mm("Early signal score",score(early)),mm("Alpha score",score(alpha)),mm("Social score",score(socialScore)),mm("Price ↔ Social direction",dir),mm("Lead / lag",ll==null?"—":`${Math.abs(ll).toFixed(1)}m`),mm("Lead/lag confidence",score(conf)),mm("Price after social 5m",signed(r5)),mm("Price after social 15m",signed(r15)),mm("Price after social 1h",signed(r60)),mm("Max upside 1h",signed(up)),mm("Max drawdown 1h",signed(dd)),mm("Nearest 5m price impulse",imp?signed(imp.change):"—"),mm("Price 1h snapshot",signed(market?.pair?.changeH1)),mm("Price 24h snapshot",signed(market?.pair?.change24h)),mm("Volume 1h",money(market?.pair?.volumeH1)),mm("Volume 24h",money(market?.pair?.volumeH24)),mm("Liquidity",money(market?.pair?.liquidityUsd))]},
  {title:"Price event evidence",rows:[mm("Trades sampled",compact(trades.length)),mm("Trade history start",trades.length?ago(trades[0].time):"—"),mm("Trade history end",trades.length?ago(trades[trades.length-1].time):"—"),mm("Price at social spike",p0?p0.price.toPrecision(6):"—","SOL price"),mm("Price +5m",p5?p5.price.toPrecision(6):"—","nearest within ±5m"),mm("Price +15m",p15?p15.price.toPrecision(6):"—","nearest within ±5m"),mm("Price +1h",p60?p60.price.toPrecision(6):"—","nearest within ±10m"),mm("Impulse timestamp",imp?ago(imp.time):"—"),mm("Impulse threshold",`${IMPULSE_PCT}% / ${IMPULSE_WINDOW/60_000}m`),mm("On-chain raw trades",compact(chain?.summary?.totalRawTrades||chain?.summary?.totalTrades)),mm("Unique wallets",compact(chain?.summary?.uniqueWallets)),mm("History truncated",chain?.truncated==null?"—":chain.truncated?"YES":"NO")]},
  {title:"AI Agent / Evidence",rows:[mm("Agent",ai?.available?`${ai.provider||"qwen"} · ${ai.model||"Qwen"}`:"unavailable"),mm("AI latency",ai?.latencyMs?`${Math.round(ai.latencyMs)} ms`:"—"),mm("AI cache",ai?.cache||"—"),mm("Summary",ar?.summary||"—"),mm("Claims",String(ar?.claims?.length||0)),mm("Entities",String(ar?.entities?.length||0)),mm("Relationships",String(ar?.relationships?.length||0)),mm("Risks",String(ar?.risks?.length||0)),mm("Originators",ar?.campaignHypothesis?.likelyOriginators?.join(", ")||"—"),mm("Amplifiers",ar?.campaignHypothesis?.amplifiers?.slice(0,6).join(", ")||"—")]}
 ];return{groups,xScore,tgScore,organic,manipulation,socialRisk,early,alpha,socialScore,price}
}

function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wider text-content-faint">{label}</span>{children}</label>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="flex min-h-10 items-center gap-2 rounded-xl border border-bg-border bg-bg-card px-3 text-xs text-content-muted"><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{label}</label>}
function Notice({tone,text}:{tone:"danger"|"warning";text:string}){return <div className={`flex gap-2 rounded-xl border p-3 text-xs ${tone==="danger"?"border-danger/30 bg-danger/10 text-danger":"border-warning/30 bg-warning/10 text-content-muted"}`}><AlertTriangle className="h-4 w-4 shrink-0"/>{text}</div>}
function Kpi({label,value,icon}:{label:string;value:string;icon:ReactNode}){return <div className="surface-panel rounded-xl border border-bg-border p-3"><div className="flex items-center justify-between text-content-faint"><span className="text-[9px] uppercase tracking-wider">{label}</span><span className="[&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span></div><div className="mt-2 font-mono text-lg font-bold text-content">{value}</div></div>}
function Table({title,rows}:{title:string;rows:Metric[]}){return <div className="overflow-hidden rounded-xl border border-bg-border"><div className="border-b border-bg-border bg-bg-elevated/60 px-3 py-2 text-xs font-semibold text-content">{title}</div><div className="divide-y divide-bg-border">{rows.map(r=><div key={r.label} className="grid grid-cols-[minmax(0,1fr)_minmax(90px,.8fr)] gap-3 px-3 py-2 text-[11px]"><div><div className="text-content-muted">{r.label}</div>{r.note&&<div className="mt-0.5 text-[9px] text-content-faint">{r.note}</div>}</div><div className="break-words text-right font-mono font-semibold text-content">{r.value}</div></div>)}</div></div>}
function PricePanel({p,loading}:{p:PriceSocial;loading:boolean}){return <section className="surface-panel rounded-2xl border border-bg-border p-4"><div className="mb-3 flex items-center gap-2"><TrendingUp className="h-4 w-4 text-primary"/><div><h2 className="text-sm font-semibold text-content">Price ↔ Social lead/lag</h2><p className="text-[10px] text-content-faint">{loading?"Trade history загружается параллельно — social уже доступен.":`Ближайший price impulse ≥ ${IMPULSE_PCT}% за 5 минут.`}</p></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><Kpi label="Direction" value={p.leadDirection} icon={<Zap/>}/><Kpi label="Lead / lag" value={p.leadLagMinutes==null?"—":`${Math.abs(p.leadLagMinutes).toFixed(1)}m`} icon={<Gauge/>}/><Kpi label="Confidence" value={score(p.leadLagConfidence)} icon={<Radar/>}/><Kpi label="+5m" value={signed(p.reaction5)} icon={<TrendingUp/>}/><Kpi label="+15m" value={signed(p.reaction15)} icon={<TrendingUp/>}/><Kpi label="+1h" value={signed(p.reaction60)} icon={<TrendingUp/>}/><Kpi label="Max up 1h" value={signed(p.maxUpside)} icon={<TrendingUp/>}/><Kpi label="Max DD 1h" value={signed(p.maxDrawdown)} icon={<ShieldAlert/>}/></div></section>}
function Ai({ai}:{ai:any}){const r=ai?.result;return <section className="surface-panel rounded-2xl border border-bg-border p-4"><div className="mb-3 flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-primary"/><h2 className="text-sm font-semibold text-content">Qwen AI · Telegram second-stage analysis</h2></div>{!ai?<div className="text-xs text-content-faint">AI запускается после Telegram сообщений.</div>:!r?<div className="text-xs text-warning">Qwen недоступен: {ai.error||"нет результата"}</div>:<div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm leading-6 text-content-soft">{r.summary}</p><div className="mt-3 rounded-xl border border-bg-border bg-bg-card p-3"><div className="text-[10px] uppercase tracking-wider text-content-faint">Campaign narrative</div><div className="mt-1 text-xs leading-5 text-content-muted">{r.campaignHypothesis?.narrative||"—"}</div></div></div><div className="space-y-2">{(r.reasoningSummary||[]).map((v:string,i:number)=><div key={i} className="rounded-lg border border-bg-border bg-bg-elevated/50 px-3 py-2 text-xs text-content-muted">{v}</div>)}</div></div>}</section>}
function TimelinePanel({x,tg,impulseAt,impulseChange}:{x:any;tg:any;impulseAt:number|null;impulseChange:number|null}){const items=useMemo(()=>{const a:Timeline[]=[...(tg?.timeline||[])];for(const t of x?.topTweets||[]){const z=ts(t.timestamp);a.push({platform:"x",source_handle:t.author,source_name:null,source_url:null,text:t.text,occurred_at:z==null?"":new Date(z).toISOString(),metrics:{likes:t.likes,retweets:t.retweets,views:t.views}})}if(impulseAt!=null)a.push({platform:"price",source_handle:"on-chain",source_name:"price impulse",source_url:null,text:`Nearest 5m impulse: ${signed(impulseChange)}`,occurred_at:new Date(impulseAt).toISOString(),metrics:null});return a.sort((p,q)=>n(ts(p.occurred_at))-n(ts(q.occurred_at))).slice(0,100)},[x,tg,impulseAt,impulseChange]);return <section className="surface-panel rounded-2xl border border-bg-border p-4"><h2 className="text-sm font-semibold text-content">Signal timeline · TG → X → Price → Hype</h2><div className="mt-3 space-y-2">{items.length?items.map((i,k)=><div key={`${k}-${i.platform}-${i.source_handle}`} className="grid grid-cols-[70px_120px_1fr] gap-2 rounded-xl border border-bg-border bg-bg-card/50 p-2 text-[10px]"><div className="font-mono text-content-faint">{i.occurred_at?new Date(i.occurred_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</div><div className="font-semibold text-content">{i.platform.toUpperCase()} · {i.source_handle||i.source_name||"source"}</div><div className="line-clamp-2 text-content-muted">{i.text}</div></div>):<div className="text-xs text-content-faint">Нет timestamped сигналов.</div>}</div></section>}
