'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
type Entity={id:string;name:string;type:string;platform:string;influence_score:number|null;risk_score:number|null};
type Detail={entity:Entity;profile:{influence_score:number|null;risk_score:number|null}|null;tags:{id:string;name:string;confidence:number}[];history:{observed_at:string;payload:{followers:number|null;bio:string|null}}[];relations:number;clusters:{id:string;name:string}[]};
async function load<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{cache:'no-store',signal});const j=await r.json();if(!r.ok)throw new Error(j.error??'Не удалось загрузить данные');return j.data;}
const score=(v:number|null|undefined)=>v==null?'Не рассчитано':Math.round(v*100)+'%';
export default function IntelligencePage(){
 const [entities,setEntities]=useState<Entity[]>([]),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[counts,setCounts]=useState<Record<string,string>>({});
 useEffect(()=>{const c=new AbortController();load<Record<string,string>>('/api/intelligence/overview',c.signal).then(setCounts).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');load<Entity[]>('/api/entities?limit=50&offset='+offset+'&q='+encodeURIComponent(search),c.signal).then(setEntities).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[offset,search]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();setDetail(null);load<Detail>('/api/entities/'+selected,c.signal).then(setDetail).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[selected]);
 const history=detail?.history.filter(h=>h.payload.followers!=null).slice().reverse()??[],maximum=Math.max(1,...history.map(h=>h.payload.followers!));
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
  <Link href="/settings" className="text-primary">← Настройки X Collector</Link><h1 className="text-2xl font-bold">Intelligence: сущности и доказательства</h1>
  <p className="text-content-muted">Теги описывают наблюдаемые темы. Влияние — относительный PageRank в собранном графе аккаунтов. Отсутствие оценки риска не означает низкий риск.</p>
  <div className="flex flex-wrap gap-4">{[['entities','Сущности'],['raw_events','Наблюдения'],['pending','Ожидают обработки'],['relations','Связи'],['snapshots','Снимки']].map(([key,label])=><div key={key} className="surface-panel p-3"><span className="text-content-muted">{label}: </span><strong>{counts[key]??'…'}</strong></div>)}</div>
  <form onSubmit={e=>{e.preventDefault();setOffset(0);setSearch(query);}} className="flex gap-2"><input aria-label="Поиск сущностей" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} placeholder="Имя аккаунта или тема" className="min-w-0 flex-1 rounded border border-white/20 bg-transparent p-2"/><button className="rounded border border-white/20 px-4">Найти</button></form>
  {error&&<p role="alert" className="text-red-400">{error}</p>}{busy&&<p role="status">Загрузка…</p>}
  <div className="grid gap-6 lg:grid-cols-2"><section className="surface-panel p-4"><h2 className="mb-3 font-bold">Сущности</h2>{!busy&&!entities.length&&<p>Пока нет сущностей по этому запросу.</p>}<ul className="divide-y divide-white/10">{entities.map(e=><li key={e.id}><button onClick={()=>setSelected(e.id)} className="w-full py-3 text-left"><strong>{e.name}</strong><span className="ml-3 text-sm text-content-muted">{e.type} · {e.platform}</span></button></li>)}</ul><div className="mt-3 flex justify-between gap-3"><button disabled={offset===0||busy} onClick={()=>setOffset(v=>Math.max(0,v-50))}>← Предыдущие</button><button disabled={entities.length<50||busy} onClick={()=>setOffset(v=>v+50)}>Следующие →</button></div></section>
  <section className="surface-panel space-y-4 p-4">{detail?<><h2 className="text-xl font-bold">{detail.entity.name}</h2><p>Влияние: {score(detail.profile?.influence_score)} · Риск: {score(detail.profile?.risk_score)}</p><div className="flex flex-wrap gap-2">{detail.tags.map(t=><span key={t.id} className="rounded border border-white/20 p-1 text-sm">{t.name} · {Math.round(t.confidence*100)}%</span>)}</div><p>Связи: {detail.relations}</p><Link href={'/api/graph/relations?entity='+detail.entity.id} className="text-primary">Посмотреть связи и ID для проверки доказательств</Link><p>Кластеры: {detail.clusters.map(c=>c.name).join(', ')||'Не рассчитаны'}</p><h3 className="font-bold">История подписчиков</h3>{history.length>1?<svg viewBox="0 0 500 160" role="img" aria-label="Изменение числа подписчиков по наблюдениям" className="w-full"><polyline fill="none" stroke="currentColor" strokeWidth="2" points={history.map((h,i)=>`${10+i*480/(history.length-1)},${145-h.payload.followers!/maximum*130}`).join(' ')}/></svg>:<p>Для графика нужны хотя бы два наблюдения.</p>}<ul className="max-h-64 overflow-auto text-sm">{detail.history.map((h,i)=><li key={i} className="py-1">{new Date(h.observed_at).toLocaleString('ru-RU')} · Подписчики: {h.payload.followers??'Неизвестно'}</li>)}</ul></>:<p>Выберите сущность для просмотра профиля и истории.</p>}</section></div>
 </main>;
}
