export const MINT_RE = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
export const IMPULSE_WINDOW_MS = 5 * 60_000;
export const IMPULSE_THRESHOLD_PCT = 10;
const HOUR_MS = 60 * 60_000;

export type Lookback = "1" | "6" | "24" | "72" | "168" | "720" | "all";
export type SocialOptions = {
  symbol: string;
  lookback: Lookback;
  xLimit: number;
  xVerifiedOnly: boolean;
  xExcludeSuspicious: boolean;
  tgLimit: number;
  tgMinChannelScore: number;
  tgExplicitCallsOnly: boolean;
};
export type TimelineItem = {
  platform: string;
  event_type?: string;
  source_handle: string | null;
  source_name: string | null;
  source_url: string | null;
  text: string;
  occurred_at: string;
  metrics: Record<string, unknown> | null;
};
export type Tweet = { id: string; text: string; author: string; likes: number; retweets: number; views: number; timestamp: number | null; isSuspicious: boolean };
export type Shiller = { handle: string; tweets: number; totalEngagement: number; isBot: boolean; followers: number | null; postsCount: number | null; isVerified: boolean };
export type TwitterStats = {
  symbol: string;
  totalTweets: number;
  totalViews: number;
  totalLikes: number;
  totalRetweets: number;
  uniqueMentioners: number;
  botRiskScore: number;
  anomalyCount: number;
  topTweets: Tweet[];
  shillers: Shiller[];
  aggregated: { totalEngagement: number; engagementRate: number; verifiedAuthors: number; botRatio: number };
};
export type SocialTimeline = { mentions: number; platforms: Record<string, number>; origin: TimelineItem | null; timeline: TimelineItem[] };
export type Channel = { username: string | null; title: string; score: number; win_rate: number; rug_rate: number };
export type Market = { pair?: { name?: string; createdAt?: number | null; changeH1?: number | null; change24h?: number | null; volumeH1?: number | null; volumeH24?: number | null; liquidityUsd?: number | null } };
export type ChainAnalysis = { trades?: Array<{ ts: number; p: number }>; truncated?: boolean; summary?: { totalRawTrades?: number; totalTrades?: number; uniqueWallets?: number } };
export type AiResult = {
  summary?: string;
  dominantIntent?: string;
  sentiment?: { label?: string; score?: number; confidence?: number };
  coordinationSignals?: Array<{ severity?: string }>;
  risks?: Array<{ severity?: string }>;
  claims?: unknown[];
  entities?: unknown[];
  relationships?: unknown[];
  reasoningSummary?: string[];
  overallConfidence?: number;
  campaignHypothesis?: { label?: string; confidence?: number; narrative?: string; likelyOriginators?: string[]; amplifiers?: string[] };
};
export type AiEnvelope = { agent?: string; available?: boolean; provider?: string; model?: string; latencyMs?: number; cache?: string; error?: string; result?: AiResult };
export type Metric = { label: string; value: string; note?: string };
export type PriceSocial = { socialSpikeTime: number | null; reaction5: number | null; reaction15: number | null; reaction60: number | null; maxUpside: number | null; maxDrawdown: number | null; impulseTime: number | null; impulseChange: number | null; leadLagMinutes: number | null; leadDirection: string; leadLagConfidence: number | null; tradeCount: number };
export type DerivedSocial = { groups: Array<{ title: string; rows: Metric[] }>; xScore: number; tgScore: number; organic: number; manipulation: number; socialRisk: number; early: number; alpha: number; socialScore: number; price: PriceSocial };

type TradePoint = { time: number; price: number };

export const DEFAULT_SOCIAL_OPTIONS: SocialOptions = { symbol: "", lookback: "24", xLimit: 40, xVerifiedOnly: false, xExcludeSuspicious: true, tgLimit: 200, tgMinChannelScore: 0, tgExplicitCallsOnly: false };

export function numberOr(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
export function clamp(value: number, min = 0, max = 100) { return Math.max(min, Math.min(max, value)); }
function hasNumber(value: unknown) { return value !== null && value !== undefined && value !== "" && Number.isFinite(Number(value)); }
export function compact(value: unknown) { return hasNumber(value) ? new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 }).format(Number(value)) : "—"; }
export function pct(value: unknown) { return hasNumber(value) ? `${Number(value).toFixed(1)}%` : "—"; }
export function signedPct(value: unknown) { return hasNumber(value) ? `${Number(value) >= 0 ? "+" : ""}${Number(value).toFixed(1)}%` : "—"; }
export function score(value: unknown) { return hasNumber(value) ? `${Math.round(Number(value))}/100` : "—"; }
export function money(value: unknown) { return hasNumber(value) ? `$${compact(value)}` : "—"; }
export function toTimestamp(value: unknown) { if (value == null || value === "") return null; let parsed = typeof value === "number" ? value : Date.parse(String(value)); if (!Number.isFinite(parsed)) return null; if (parsed < 1e12) parsed *= 1000; return parsed; }
export function ago(value: unknown, now = Date.now()) { const timestamp = toTimestamp(value); if (timestamp == null) return "—"; const minutes = Math.max(0, Math.round((now - timestamp) / 60_000)); return minutes < 60 ? `${minutes}m` : minutes < 2880 ? `${Math.round(minutes / 60)}h` : `${Math.round(minutes / 1440)}d`; }
export function upsertWarning(warnings: string[], message: string) { const key = message.split(":", 1)[0]; return [...warnings.filter((item) => item.split(":", 1)[0] !== key), message]; }

const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return 0; const m = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[m] : (sorted[m - 1] + sorted[m]) / 2; };
const normalizeText = (value: string) => value.toLowerCase().replace(/https?:\/\/\S+/g, " ").replace(/[1-9A-HJ-NP-Za-km-z]{32,44}/g, " ").replace(/[^\p{L}\p{N}]+/gu, " ").trim().slice(0, 220);
const normalizeRatePct = (value: unknown) => { if (!hasNumber(value)) return null; const parsed = Number(value); return clamp(Math.abs(parsed) <= 1 ? parsed * 100 : parsed); };
const growthPct = (current: number, previous: number) => previous > 0 ? ((current - previous) / previous) * 100 : null;
const metric = (label: string, value: string, note?: string): Metric => ({ label, value, note });

function sentiment(texts: string[]) {
  const positive = /\b(bull|bullish|buy|gem|moon|pump|breakout|alpha|early|strong|ape|send|upside|good|great|лонг|покуп|ракета|рост|гем)\b|🚀|🔥|📈|💎/i;
  const negative = /\b(rug|scam|dump|sell|exit|dead|avoid|warning|bear|rekt|скам|раг|слив|продаж|паден)\b|⚠|📉|☠/i;
  let pos = 0, neg = 0, neutral = 0;
  for (const text of texts) { const p = positive.test(text), n = negative.test(text); if (p && !n) pos++; else if (n && !p) neg++; else neutral++; }
  const total = pos + neg + neutral;
  return total ? { label: pos / total > .52 ? "BULLISH" : neg / total > .38 ? "BEARISH" : "MIXED", p: pos / total * 100, n: neg / total * 100, u: neutral / total * 100 } : { label: "—", p: 0, n: 0, u: 0 };
}
function sentimentDelta(rows: Array<{ time: number | null; text: string }>) { const sorted = rows.filter((row): row is { time: number; text: string } => row.time != null).sort((a, b) => a.time - b.time); if (sorted.length < 4) return null; const m = Math.floor(sorted.length / 2); return sentiment(sorted.slice(m).map((row) => row.text)).p - sentiment(sorted.slice(0, m).map((row) => row.text)).p; }
function windowStats<T>(rows: T[], timeOf: (row: T) => number | null, keyOf: (row: T) => unknown, now: number) { const counts = { m5: 0, m15: 0, h1: 0, h6: 0, h24: 0 }; const unique6 = new Set<string>(), uniquePrev6 = new Set<string>(), unique24 = new Set<string>(); for (const row of rows) { const time = timeOf(row); if (time == null) continue; const age = now - time; if (age < 0) continue; if (age <= 5 * 60_000) counts.m5++; if (age <= 15 * 60_000) counts.m15++; if (age <= HOUR_MS) counts.h1++; if (age <= 6 * HOUR_MS) counts.h6++; if (age <= 24 * HOUR_MS) counts.h24++; const key = keyOf(row); if (!key) continue; const normalized = String(key).toLowerCase(); if (age <= 6 * HOUR_MS) unique6.add(normalized); else if (age <= 12 * HOUR_MS) uniquePrev6.add(normalized); if (age <= 24 * HOUR_MS) unique24.add(normalized); } return { ...counts, unique6: unique6.size, uniquePrev6: uniquePrev6.size, unique24: unique24.size }; }
function densestWindowTime(times: number[], windowMs = 5 * 60_000) { const sorted = [...times].sort((a, b) => a - b); if (!sorted.length) return null; let bestStart = 0, bestEnd = 0, end = 0; for (let start = 0; start < sorted.length; start++) { if (end < start) end = start; while (end + 1 < sorted.length && sorted[end + 1] - sorted[start] <= windowMs) end++; if (end - start > bestEnd - bestStart) { bestStart = start; bestEnd = end; } } return sorted[Math.floor((bestStart + bestEnd) / 2)]; }
function lowerBound(trades: TradePoint[], target: number) { let low = 0, high = trades.length; while (low < high) { const middle = (low + high) >> 1; if (trades[middle].time < target) low = middle + 1; else high = middle; } return low; }
function priceAtOrBefore(trades: TradePoint[], target: number, toleranceMs: number) { const index = lowerBound(trades, target); const candidate = index < trades.length && trades[index].time === target ? trades[index] : trades[index - 1]; return candidate && target - candidate.time <= toleranceMs ? candidate : null; }
function priceAtOrAfter(trades: TradePoint[], target: number, toleranceMs: number) { const candidate = trades[lowerBound(trades, target)]; return candidate && candidate.time - target <= toleranceMs ? candidate : null; }
function priceNear(trades: TradePoint[], target: number, toleranceMs: number) { const index = lowerBound(trades, target), before = trades[index - 1], after = trades[index]; const candidate = !before ? after : !after ? before : target - before.time <= after.time - target ? before : after; return candidate && Math.abs(candidate.time - target) <= toleranceMs ? candidate : null; }
function priceChange(a: TradePoint | null, b: TradePoint | null) { return a && b && a.price > 0 ? (b.price - a.price) / a.price * 100 : null; }
function findPriceImpulse(trades: TradePoint[], socialTime: number | null) { let best: { time: number; change: number } | null = null; for (const trade of trades) { if (socialTime != null && Math.abs(trade.time - socialTime) > 6 * HOUR_MS) continue; const base = priceAtOrBefore(trades, trade.time - IMPULSE_WINDOW_MS, IMPULSE_WINDOW_MS); if (!base || base.price <= 0) continue; const change = (trade.price - base.price) / base.price * 100; if (Math.abs(change) < IMPULSE_THRESHOLD_PCT) continue; if (!best || socialTime == null || Math.abs(trade.time - socialTime) < Math.abs(best.time - socialTime)) best = { time: trade.time, change }; } return best; }

export function deriveSocialMetrics(x: TwitterStats | null, tg: SocialTimeline | null, market: Market | null, chain: ChainAnalysis | null, ai: AiEnvelope | null, channels: Channel[], options: SocialOptions): DerivedSocial {
  const now = Date.now(), tweets = x?.topTweets || [], telegramItems = (tg?.timeline || []).filter((item) => !item.platform || item.platform.toLowerCase() === "telegram");
  const xTimes = tweets.map((tweet) => toTimestamp(tweet.timestamp)), tgTimes = telegramItems.map((item) => toTimestamp(item.occurred_at));
  const hours = Math.max(1, options.lookback === "all" ? 720 : Number(options.lookback)), xMentions = x?.totalTweets || 0, tgMentions = tg?.platforms?.telegram ?? telegramItems.length, xVelocity = xMentions / hours, tgVelocity = tgMentions / hours;
  const xWindow = windowStats(tweets, (tweet) => toTimestamp(tweet.timestamp), (tweet) => tweet.author, now), tgWindow = windowStats(telegramItems, (item) => toTimestamp(item.occurred_at), (item) => item.source_handle || item.source_name, now);
  const xAcceleration = xWindow.m15 ? clamp((xWindow.m5 / 5) / (xWindow.m15 / 15) * 50) : 0, tgAcceleration = tgWindow.m15 ? clamp((tgWindow.m5 / 5) / (tgWindow.m15 / 15) * 50) : 0;
  const xSentiment = sentiment(tweets.map((tweet) => tweet.text)), tgSentiment = sentiment(telegramItems.map((item) => item.text));
  const xSentimentDelta = sentimentDelta(tweets.map((tweet) => ({ time: toTimestamp(tweet.timestamp), text: tweet.text }))), tgSentimentDelta = sentimentDelta(telegramItems.map((item) => ({ time: toTimestamp(item.occurred_at), text: item.text })));
  const authorRatio = xMentions ? clamp((x?.uniqueMentioners || 0) / xMentions * 100) : 0, verifiedRatio = x?.uniqueMentioners ? clamp((x.aggregated.verifiedAuthors || 0) / x.uniqueMentioners * 100) : 0, botRatio = normalizeRatePct(x?.aggregated.botRatio) ?? 0, botRisk = clamp(x?.botRiskScore || 0), shillers = x?.shillers || [];
  const reach = shillers.reduce((sum, account) => sum + (account.followers || 0), 0), influencers = shillers.filter((account) => account.isVerified || (account.followers || 0) >= 10_000 || account.totalEngagement >= 5_000), influencerReach = influencers.reduce((sum, account) => sum + (account.followers || 0), 0), repeatShillers = shillers.filter((account) => account.tweets >= 2).length, smartAccounts = shillers.filter((account) => !account.isBot && (account.isVerified || account.totalEngagement >= 2_500 || (account.followers || 0) >= 5_000)).length;
  const normalizedTexts = [...tweets.map((tweet) => tweet.text), ...telegramItems.map((item) => item.text)].map(normalizeText).filter((text) => text.length >= 16), frequencies = new Map<string, number>(); for (const text of normalizedTexts) frequencies.set(text, (frequencies.get(text) || 0) + 1); const copied = [...frequencies.values()].filter((count) => count > 1).reduce((sum, count) => sum + count, 0), copyRatio = normalizedTexts.length ? copied / normalizedTexts.length * 100 : 0;
  const recentXTweets = tweets.filter((tweet) => { const time = toTimestamp(tweet.timestamp); return time != null && time >= now - HOUR_MS; }), botBurst = recentXTweets.length ? recentXTweets.filter((tweet) => tweet.isSuspicious).length / recentXTweets.length * 100 : 0;
  const tgKeys = new Set(telegramItems.flatMap((item) => [item.source_handle, item.source_name].filter(Boolean).map((value) => String(value).replace(/^@/, "").toLowerCase()))), relatedChannels = channels.filter((channel) => tgKeys.has(String(channel.username || "").replace(/^@/, "").toLowerCase()) || tgKeys.has(channel.title.toLowerCase()));
  const channelScore = relatedChannels.length ? average(relatedChannels.map((channel) => clamp(numberOr(channel.score)))) : 0, winRate = average(relatedChannels.map((channel) => normalizeRatePct(channel.win_rate)).filter((value): value is number => value != null)), rugRate = average(relatedChannels.map((channel) => normalizeRatePct(channel.rug_rate)).filter((value): value is number => value != null)), explicitCalls = telegramItems.filter((item) => Boolean(item.metrics?.explicit_call || item.metrics?.is_explicit_call) || String(item.event_type || "").toLowerCase().includes("call")).length;
  const aiResult = ai?.result, aiCoordination = aiResult?.coordinationSignals?.length || 0, highAiRisks = aiResult?.risks?.filter((risk) => risk.severity === "high" || risk.severity === "critical").length || 0, coordinationScore = clamp(copyRatio * .75 + aiCoordination * 11 + repeatShillers * 3), followerQuality = clamp((100 - botRisk) * .45 + verifiedRatio * .25 + clamp(Math.log10(median(shillers.map((account) => account.followers || 0)) + 1) * 18) * .3), paid = clamp(coordinationScore * .45 + botRisk * .25 + clamp(repeatShillers * 8) * .15 + highAiRisks * 8), organic = clamp(100 - paid * .72 - copyRatio * .18 + authorRatio * .22), xScore = clamp((100 - botRisk) * .35 + authorRatio * .25 + clamp(Math.log10((x?.aggregated.totalEngagement || 0) + 1) * 20) * .25 + followerQuality * .15), tgScore = clamp(channelScore * .3 + winRate * .2 + (100 - rugRate) * .2 + clamp(tgKeys.size * 7) * .15 + clamp(explicitCalls * 8) * .15);
  const finiteX = xTimes.filter((value): value is number => value != null), finiteTg = tgTimes.filter((value): value is number => value != null), firstX = finiteX.length ? Math.min(...finiteX) : null, firstTg = finiteTg.length ? Math.min(...finiteTg) : null, both = firstX != null && firstTg != null, crossLag = both ? Math.abs(firstX - firstTg) / 60_000 : null, cross = both ? clamp(100 - Math.min(100, (crossLag || 0) / 3) + Math.min(xVelocity + tgVelocity, 20) * 2) : 0;
  const hype = clamp(average([xAcceleration, tgAcceleration, clamp((xVelocity + tgVelocity) * 10), clamp((x?.aggregated.engagementRate || 0) * 100)])), fomo = clamp(hype * .55 + Math.max(xSentiment.p, tgSentiment.p) * .25 + clamp(explicitCalls * 7) * .2), manipulation = clamp(paid * .7 + coordinationScore * .3), socialRisk = clamp(manipulation * .4 + botRisk * .24 + rugRate * .14 + (100 - organic) * .12 + Math.min(100, highAiRisks * 18) * .1), riskLevel = socialRisk >= 70 ? "HIGH" : socialRisk >= 40 ? "MEDIUM" : "LOW";
  const created = toTimestamp(market?.pair?.createdAt), firstSocial = firstX == null ? firstTg : firstTg == null ? firstX : Math.min(firstX, firstTg), earlyMinutes = created != null && firstSocial != null ? Math.max(0, (firstSocial - created) / 60_000) : null, early = earlyMinutes == null ? clamp(70 - Math.min(60, (xMentions + tgMentions) / 10)) : clamp(100 - earlyMinutes / 12), alpha = clamp(early * .35 + organic * .25 + (100 - manipulation) * .2 + cross * .2), socialScore = clamp(xScore * .36 + tgScore * .34 + organic * .15 + cross * .15);
  const events = [...finiteX, ...finiteTg], spike = densestWindowTime(events), trades: TradePoint[] = (chain?.trades || []).map((trade) => ({ time: toTimestamp(trade.ts), price: Number(trade.p) })).filter((trade): trade is TradePoint => trade.time != null && Number.isFinite(trade.price) && trade.price > 0).sort((a, b) => a.time - b.time), impulse = findPriceImpulse(trades, spike), p0 = spike == null ? null : priceNear(trades, spike, 5 * 60_000), p5 = spike == null ? null : priceAtOrAfter(trades, spike + 5 * 60_000, 5 * 60_000), p15 = spike == null ? null : priceAtOrAfter(trades, spike + 15 * 60_000, 5 * 60_000), p60 = spike == null ? null : priceAtOrAfter(trades, spike + HOUR_MS, 10 * 60_000), r5 = priceChange(p0, p5), r15 = priceChange(p0, p15), r60 = priceChange(p0, p60), oneHour = spike == null ? [] : trades.filter((trade) => trade.time >= spike && trade.time <= spike + HOUR_MS), maxPrice = oneHour.length ? Math.max(...oneHour.map((trade) => trade.price)) : null, minPrice = oneHour.length ? Math.min(...oneHour.map((trade) => trade.price)) : null, maxUp = p0 && maxPrice != null ? (maxPrice - p0.price) / p0.price * 100 : null, maxDd = p0 && minPrice != null ? (minPrice - p0.price) / p0.price * 100 : null, leadLag = spike != null && impulse ? (impulse.time - spike) / 60_000 : null, direction = leadLag == null ? "—" : Math.abs(leadLag) <= 2 ? "SYNC" : leadLag > 0 ? "SOCIAL → PRICE" : "PRICE → SOCIAL", confidence = leadLag == null ? null : clamp(35 + Math.min(35, events.length * 1.5) + Math.min(30, trades.length / 20));
  const price: PriceSocial = { socialSpikeTime: spike, reaction5: r5, reaction15: r15, reaction60: r60, maxUpside: maxUp, maxDrawdown: maxDd, impulseTime: impulse?.time ?? null, impulseChange: impulse?.change ?? null, leadLagMinutes: leadLag, leadDirection: direction, leadLagConfidence: confidence, tradeCount: trades.length };
  const firstXAuthor = [...tweets].filter((tweet) => toTimestamp(tweet.timestamp) != null).sort((a, b) => numberOr(toTimestamp(a.timestamp)) - numberOr(toTimestamp(b.timestamp)))[0]?.author || "—", firstTgSource = tg?.origin?.source_handle || tg?.origin?.source_name || [...telegramItems].sort((a, b) => numberOr(toTimestamp(a.occurred_at)) - numberOr(toTimestamp(b.occurred_at)))[0]?.source_handle || "—", sentimentChanges = [xSentimentDelta, tgSentimentDelta].filter((value): value is number => value != null), combinedDelta = sentimentChanges.length ? average(sentimentChanges) : null, narrative = aiResult?.campaignHypothesis?.narrative || "—", campaign = aiResult?.campaignHypothesis?.label || "—";
  const groups: DerivedSocial["groups"] = [
    { title: "X / Twitter", rows: [metric("X score", score(xScore)), metric("Mentions", compact(xMentions)), metric("Mentions 5m", String(xWindow.m5), "sampled top posts"), metric("Mentions 15m", String(xWindow.m15), "sampled top posts"), metric("Mentions 1h", String(xWindow.h1), "sampled top posts"), metric("Mentions 6h", String(xWindow.h6), "sampled top posts"), metric("Mentions 24h", String(xWindow.h24), "sampled top posts"), metric("Mentions / h", xVelocity.toFixed(2)), metric("Acceleration", score(xAcceleration)), metric("Unique authors", compact(x?.uniqueMentioners)), metric("Unique authors 6h", String(xWindow.unique6), "sampled top posts"), metric("Unique authors 24h", String(xWindow.unique24), "sampled top posts"), metric("Author growth 6h", signedPct(growthPct(xWindow.unique6, xWindow.uniquePrev6)), "vs previous 6h"), metric("Author diffusion", pct(authorRatio)), metric("Views", compact(x?.totalViews)), metric("Likes", compact(x?.totalLikes)), metric("Reposts", compact(x?.totalRetweets)), metric("Engagement", compact(x?.aggregated.totalEngagement)), metric("Engagement rate", x ? pct(x.aggregated.engagementRate * 100) : "—"), metric("Verified authors", compact(x?.aggregated.verifiedAuthors)), metric("Verified ratio", x ? pct(verifiedRatio) : "—"), metric("Influencers", x ? String(influencers.length) : "—"), metric("Potential reach", x ? compact(reach) : "—"), metric("Influencer reach", x ? compact(influencerReach) : "—"), metric("Smart accounts", x ? String(smartAccounts) : "—"), metric("Repeat shillers", x ? String(repeatShillers) : "—"), metric("Bot risk", x ? score(botRisk) : "—"), metric("Bot ratio", x ? pct(botRatio) : "—"), metric("Bot burst 1h", x ? pct(botBurst) : "—"), metric("Anomalies", x ? String(x.anomalyCount || 0) : "—"), metric("Follower quality", x ? score(followerQuality) : "—"), metric("Sentiment", x ? xSentiment.label : "—"), metric("Positive", x ? pct(xSentiment.p) : "—"), metric("Neutral", x ? pct(xSentiment.u) : "—"), metric("Negative", x ? pct(xSentiment.n) : "—"), metric("Sentiment change", x ? signedPct(xSentimentDelta) : "—"), metric("First mover", x ? firstXAuthor : "—"), metric("First mention", firstX != null ? ago(firstX, now) : "—"), metric("Account age", "—", "X collector does not expose account creation date")] },
    { title: "Telegram", rows: [metric("TG score", score(tgScore)), metric("Mentions", compact(tgMentions)), metric("Mentions 5m", tg ? String(tgWindow.m5) : "—"), metric("Mentions 15m", tg ? String(tgWindow.m15) : "—"), metric("Mentions 1h", tg ? String(tgWindow.h1) : "—"), metric("Mentions 6h", tg ? String(tgWindow.h6) : "—"), metric("Mentions 24h", tg ? String(tgWindow.h24) : "—"), metric("Mentions / h", tg ? tgVelocity.toFixed(2) : "—"), metric("Acceleration", tg ? score(tgAcceleration) : "—"), metric("Channels", tg ? String(tgKeys.size) : "—"), metric("Channels 6h", tg ? String(tgWindow.unique6) : "—"), metric("Channels 24h", tg ? String(tgWindow.unique24) : "—"), metric("Channel growth 6h", tg ? signedPct(growthPct(tgWindow.unique6, tgWindow.uniquePrev6)) : "—", "vs previous 6h"), metric("Explicit calls", tg ? String(explicitCalls) : "—"), metric("Channel score", relatedChannels.length ? score(channelScore) : "—"), metric("Historical win rate", winRate || relatedChannels.length ? pct(winRate) : "—"), metric("Historical rug rate", rugRate || relatedChannels.length ? pct(rugRate) : "—"), metric("Sentiment", aiResult?.sentiment?.label || (tg ? tgSentiment.label : "—")), metric("AI sentiment score", aiResult?.sentiment?.score != null ? numberOr(aiResult.sentiment.score).toFixed(2) : "—"), metric("AI sentiment confidence", aiResult?.sentiment?.confidence != null ? pct(numberOr(aiResult.sentiment.confidence) * 100) : "—"), metric("Window sentiment change", tg ? signedPct(tgSentimentDelta) : "—"), metric("Dominant intent", aiResult?.dominantIntent || "—"), metric("Top/first source", tg ? firstTgSource : "—"), metric("First signal", firstTg != null ? ago(firstTg, now) : "—"), metric("AI campaign", campaign), metric("AI coordination signals", aiResult ? String(aiCoordination) : "—"), metric("AI high risks", aiResult ? String(highAiRisks) : "—"), metric("AI overall confidence", aiResult?.overallConfidence != null ? pct(numberOr(aiResult.overallConfidence) * 100) : "—")] },
    { title: "Growth / Quality / Manipulation", rows: [metric("Hype score", score(hype)), metric("FOMO score", score(fomo)), metric("Organic score", score(organic)), metric("Paid promotion risk", score(paid)), metric("Manipulation score", score(manipulation)), metric("Social risk", score(socialRisk)), metric("Social risk level", riskLevel), metric("Coordination score", score(coordinationScore)), metric("Copy-paste ratio", pct(copyRatio)), metric("Follower quality", score(followerQuality)), metric("Narrative strength", score(clamp(hype * .45 + cross * .25 + numberOr(aiResult?.campaignHypothesis?.confidence) * 30))), metric("Narrative", narrative), metric("Campaign hypothesis", campaign), metric("Peak velocity", `${Math.max(xVelocity, tgVelocity).toFixed(2)}/h`), metric("Velocity change", score(average([xAcceleration, tgAcceleration]))), metric("Sentiment change", signedPct(combinedDelta), "positive-share change inside window")] },
    { title: "Cross-platform / Timing", rows: [metric("Cross-platform score", score(cross)), metric("Both platforms active", both ? "YES" : "NO"), metric("TG → X lag", firstX != null && firstTg != null && firstTg <= firstX ? `${Math.round((firstX - firstTg) / 60_000)}m` : "—"), metric("X → TG lag", firstX != null && firstTg != null && firstX < firstTg ? `${Math.round((firstTg - firstX) / 60_000)}m` : "—"), metric("First X", firstX != null ? ago(firstX, now) : "—"), metric("First TG", firstTg != null ? ago(firstTg, now) : "—"), metric("Social spike", spike == null ? "—" : ago(spike, now), "densest 5m window"), metric("Early signal score", score(early)), metric("Alpha score", score(alpha)), metric("Social score", score(socialScore)), metric("Price ↔ Social direction", direction), metric("Lead / lag", leadLag == null ? "—" : `${Math.abs(leadLag).toFixed(1)}m`), metric("Lead/lag confidence", score(confidence)), metric("Price after social 5m", signedPct(r5)), metric("Price after social 15m", signedPct(r15)), metric("Price after social 1h", signedPct(r60)), metric("Max upside 1h", signedPct(maxUp)), metric("Max drawdown 1h", signedPct(maxDd)), metric("Nearest 5m price impulse", impulse ? signedPct(impulse.change) : "—"), metric("Price 1h snapshot", signedPct(market?.pair?.changeH1)), metric("Price 24h snapshot", signedPct(market?.pair?.change24h)), metric("Volume 1h", money(market?.pair?.volumeH1)), metric("Volume 24h", money(market?.pair?.volumeH24)), metric("Liquidity", money(market?.pair?.liquidityUsd))] },
    { title: "Price event evidence", rows: [metric("Trades sampled", chain ? compact(trades.length) : "—"), metric("Trade history start", trades.length ? ago(trades[0].time, now) : "—"), metric("Trade history end", trades.length ? ago(trades[trades.length - 1].time, now) : "—"), metric("Price at social spike", p0 ? p0.price.toPrecision(6) : "—", "SOL price"), metric("Price +5m", p5 ? p5.price.toPrecision(6) : "—", "first trade at/after target within 5m"), metric("Price +15m", p15 ? p15.price.toPrecision(6) : "—", "first trade at/after target within 5m"), metric("Price +1h", p60 ? p60.price.toPrecision(6) : "—", "first trade at/after target within 10m"), metric("Impulse timestamp", impulse ? ago(impulse.time, now) : "—"), metric("Impulse threshold", `${IMPULSE_THRESHOLD_PCT}% / ${IMPULSE_WINDOW_MS / 60_000}m`), metric("On-chain raw trades", compact(chain?.summary?.totalRawTrades ?? chain?.summary?.totalTrades)), metric("Unique wallets", compact(chain?.summary?.uniqueWallets)), metric("History truncated", chain?.truncated == null ? "—" : chain.truncated ? "YES" : "NO")] },
    { title: "AI Agent / Evidence", rows: [metric("Agent", ai?.available ? `${ai.provider || "qwen"} · ${ai.model || "Qwen"}` : ai ? "unavailable" : "—"), metric("AI latency", ai?.latencyMs != null ? `${Math.round(ai.latencyMs)} ms` : "—"), metric("AI cache", ai?.cache || "—"), metric("Summary", aiResult?.summary || "—"), metric("Claims", aiResult ? String(aiResult.claims?.length || 0) : "—"), metric("Entities", aiResult ? String(aiResult.entities?.length || 0) : "—"), metric("Relationships", aiResult ? String(aiResult.relationships?.length || 0) : "—"), metric("Risks", aiResult ? String(aiResult.risks?.length || 0) : "—"), metric("Originators", aiResult?.campaignHypothesis?.likelyOriginators?.join(", ") || "—"), metric("Amplifiers", aiResult?.campaignHypothesis?.amplifiers?.slice(0, 6).join(", ") || "—")] }
  ];
  return { groups, xScore, tgScore, organic, manipulation, socialRisk, early, alpha, socialScore, price };
}
